    .section .text,"ax"

/* Build 0181: PC090OJ helper mirror sizing is build-time configurable.  The
 * include is generated by apps/rastan-direct/Makefile from PC090OJ_MIRROR_RECORDS
 * (default 256; override e.g. `make release PC090OJ_MIRROR_RECORDS=128`).  It
 * defines PC090OJ_MIRROR_RECORDS, PC090OJ_MIRROR_BYTES (=RECORDS*8) and
 * PC090OJ_BITSET_BYTES (=ceil(RECORDS/8)).  All mirror array sizes, record loop
 * bounds, and the not-found record sentinel derive from these so no scattered
 * assembly constant needs hand-editing. */
    .include "pc090oj_config.inc"

    .global genesistan_pc090oj_hook_target_3b902
    .global genesistan_pc090oj_hook_target_3b926
    .global genesistan_pc090oj_hook_target_3b930
    .global genesistan_pc090oj_hook_target_41dae
    .global genesistan_pc090oj_hook_target_41f5e
    .global genesistan_pc090oj_hook_target_45dfa
    .global genesistan_pc090oj_hook_target_59f5e
    .global genesistan_hook_3ad44_dispatch
    .global genesistan_pc090oj_hook_init_priority_3ad84
    .global genesistan_pc090oj_hook_score_digit_3b802
    .global genesistan_pc090oj_hook_slot_init_54052
    .global genesistan_pc090oj_hook_player_aux_native_54810
    .global genesistan_pc090oj_hook_sprite_decay_5607c
    .global genesistan_pc090oj_hook_copy_56114
    .global genesistan_pc090oj_hook_zero_fill_56440
    .global genesistan_pc090oj_hook_status_sprite_5a098
    .global native_frontend_hud_emit
    .global genesistan_pc090oj_hook_audit_guard
    .global genesistan_pc090oj_ctrl_set_1
    .global genesistan_pc090oj_ctrl_set_0
    .global genesistan_pc090oj_sprite_ctrl_write_d0
    .global genesistan_pc090oj_sprite_ctrl_clear

    .global vdp_prepare_sprites
    .global vdp_commit_sprites
    .global vdp_commit_sprites_vram
    .global genesistan_pc090oj_dma_self_test

    .global pc090oj_ctrl_shadow
    .global pc090oj_sprite_ctrl_shadow
    .global pc090oj_emitted_count
    .global pc090oj_dropped_count
    .global native_sprite_emit
    .global native_sprite_lane
    .global native_player_frame_begin
    .global native_player_front_begin
    .global native_player_body_begin
    .global native_player_piece
    .global native_player_body_anchor_piece
    .global native_player_body_anchor_blank
    .global native_player_body_anchor_clear

    .global staged_sprite_sat
    .global sprite_tile_resident_code
    .global pc090oj_tile_dma_worklist
    .global pc090oj_tile_dma_count

    /* Build 0142 retained-identity translation state.  The player-specific
     * work-RAM tuple bridges were retired by the native main-loop player
     * producers; the remaining tables support frontend compatibility. */
    /* pc090oj_stage_block2c8 / stage_record46 removed (Build 0261): dead uncalled
     * gameplay record producers that called the relocated expander 0x3D254. */
    .global worklist_entry_for_slot
    .global pc090oj_sat_dirty

    .global audit_guard_caller_pc
    .global audit_guard_register_snapshot
    .global audit_guard_fired_flag
    .global audit_guard_vcount
    .global audit_guard_heartbeat

    .global pc090oj_dma_test_fired_flag
    .global pc090oj_dma_test_mismatch_offset
    .global pc090oj_dma_test_expected_word
    .global pc090oj_dma_test_actual_word
    .global pc090oj_dma_test_actual_buffer
    .global pc090oj_dma_test_heartbeat

    .extern rastan_pc090oj
    .extern rastan_pc090oj_hud_white
    .extern pc090oj_slot_lut
    .extern genesistan_current_scene_id
    .equ    PC090OJ_SCENE_GAMEPLAY_ID, 1
    .extern palette_route_lookup
    /* Build 0208: PROUTE owner id for PC090OJ, matching the constant table in
     * palette_hooks.s (PROUTE_OWNER_PC090OJ = 3). */
    .equ    PROUTE_OWNER_PC090OJ_ID, 3
    .global pc090oj_hud_suppressed_count
    .extern pc090oj_blank_code_bitset
    .extern pc090oj_opaque_bbox
    .extern genesistan_hook_tilemap_bg_fill
    .extern genesistan_hook_tilemap_fg_fill
    .extern genesistan_hook_pc080sn_bg_scroll_fill
    .extern genesistan_hook_pc080sn_fg_scroll_fill

    .equ VDP_DATA,      0x00C00000
    .equ VDP_CTRL,      0x00C00004
    .equ SPRITE_TILE_BASE, 1339
    .equ ARCADE_ROM_BASE, 0x00000200
    .equ PC090OJ_HW_BASE, 0x00D00000
    /* Active mirrored HW window tracks the configured record count so that when
     * PC090OJ_MIRROR_RECORDS < 256 the address-based mirror writers reject
     * out-of-range records instead of overflowing the smaller mirror array. */
    .equ PC090OJ_HW_ACTIVE_END, (PC090OJ_HW_BASE + PC090OJ_MIRROR_BYTES)
    /* Arcade A5 work-RAM base.  Absolute arcade work-RAM pointers (0x0010Cxxx)
     * map to Genesis WRAM as a5 + (pointer - ARCADE_WORKRAM_A5_BASE); the Genesis
     * a5 (0x00FF0000) corresponds to this arcade base (arcade 0x0010C000 ->
     * Genesis 0x00FF0000, e.g. the ranking table names at 0x00FF0157). */
    .equ ARCADE_WORKRAM_A5_BASE, 0x0010C000
    /* Arcade 0x59F5E clears 8 PC090OJ records starting at HW 0x00D00048
     * (= PC090OJ_HW_BASE + record 9), i.e. records 9..16.  It never touches the
     * HIGH SCORE label records 4..8.  (Build 0149 fix: the translation cleared
     * records 0..7, wiping label records 4..7 on coin insertion -> only "RE"
     * remained above 273100.) */
    .equ HOOK_59F5E_CLEAR_FIRST_RECORD, 9   /* (0x00D00048 - PC090OJ_HW_BASE) / 8 */
    .equ HOOK_59F5E_CLEAR_RECORD_COUNT, 8
    .equ PC090OJ_BLOCK2C8_BASE_RECORD, 140
    .equ PC090OJ_BLOCK2C8_APPLIED_RECORDS, (8 * 10 + 19)
    .equ PC090OJ_BLOCK2C8_SCRATCH_RECORDS, 100
    .equ PC090OJ_BLOCK2C8_SCRATCH_BYTES, (PC090OJ_BLOCK2C8_SCRATCH_RECORDS * 8)
    .if PC090OJ_BLOCK2C8_APPLIED_RECORDS > PC090OJ_BLOCK2C8_SCRATCH_RECORDS
    .error "block A5+0x2C8 scratch too small"
    .endif
    .if (PC090OJ_BLOCK2C8_BASE_RECORD + PC090OJ_BLOCK2C8_APPLIED_RECORDS - 1) != 238
    .error "block A5+0x2C8 record span must end at record 238"
    .endif

    /* ------------------------------------------------------------------ *
     * Build 0147: PC090OJ viewport coordinate + opaque-clip constants.   *
     * Named so sprite/background alignment is easy to read and to tune   *
     * during later emulator, gameplay, and real-CRT testing.             *
     * ------------------------------------------------------------------ */
    /* 16x16 sprite cell geometry. */
    .equ PC090OJ_PATTERN_WIDTH,   16
    .equ PC090OJ_PATTERN_HEIGHT,  16
    .equ PC090OJ_PATTERN_MAX_ROW, 15    /* PC090OJ_PATTERN_HEIGHT - 1 */
    .equ PC090OJ_PATTERN_MAX_COL, 15    /* PC090OJ_PATTERN_WIDTH  - 1 */
    /* Arcade PC090OJ non-flipped coordinate inversion (MAME taito/pc090oj.cpp:
     * x = 320 - x - 16, y = 256 - y - 16 when the flip-screen ctrl bit is clear). */
    .equ PC090OJ_FLIP_X_TERM, 304       /* 320 - PC090OJ_PATTERN_WIDTH  */
    .equ PC090OJ_FLIP_Y_TERM, 240       /* 256 - PC090OJ_PATTERN_HEIGHT */
    /* Arcade -> Genesis display-origin alignment.  The background plane applies
     * VDP_DISPLAY_ORIGIN_Y_BIAS(=8) / _X_BIAS(=16) in vdp_comm.s so the arcade
     * visible-area origin (raster Y=8, per rastan.cpp set_visarea 8..247) maps to
     * Genesis display line 0.  Sprites use the SAME origin so sprite/background
     * stay vertically aligned; this also places the arcade top margin above the
     * Genesis viewport, where its records clip out naturally.  Configurable. */
    .equ PC090OJ_TO_GENESIS_Y_OFFSET, -8   /* = -VDP_DISPLAY_ORIGIN_Y_BIAS */
    .equ PC090OJ_TO_GENESIS_X_OFFSET,  0   /* frontend X already aligned; tune later */
    /* Effective sprite clip rectangle = intersection of the arcade visible area
     * (raster 8..247 -> Genesis 0..239 after the Y origin) and the Genesis output
     * viewport (0..223, 0..319).  The Genesis bounds bind; ends are exclusive. */
    .equ GENESIS_VIEWPORT_LEFT,   0
    .equ GENESIS_VIEWPORT_RIGHT,  320
    .equ GENESIS_VIEWPORT_TOP,    0
    .equ GENESIS_VIEWPORT_BOTTOM, 224
    /* Genesis SAT coordinate biases (SAT value = screen coord + bias). */
    .equ PC090OJ_SAT_Y_BIAS, 0x80
    .equ PC090OJ_SAT_X_BIAS, 0x80

/* ------------------------------------------------------------------------- */
/* Internal helpers                                                          */
/* ------------------------------------------------------------------------- */

/* d0=PC090OJ record index.  Candidate state is helper-derived; mirror remains truth. */

/* d2=byte offset inside the active 0x800-byte PC090OJ mirror. */

/* PC090OJ final teardown: the virtual object-RAM record adapters
 * (.Lpc090oj_emit_slot / .Lpc090oj_clear_slot / .Lpc090oj_mirror_write_word_a1_d0
 * / .Lpc090oj_mirror_write_byte_a1_d0) are REMOVED.  Every former producer has a
 * native Genesis owner (native_frontend_hud_emit, .Lnq_title, status/player-aux
 * lanes, .Lnq_transient_items_emit, .Lnq_gameover_emit); nothing packs an 8-byte
 * PC090OJ record any more.  Proven dead output in Build 0296 (census:
 * docs/design/Andy_pc090oj_final_retirement_census.md). */

/* ------------------------------------------------------------------------- */
/* 17 helpers                                                                */
/* ------------------------------------------------------------------------- */

/* arcade 0x03B902 -- credit-area builder for PC090OJ records 17..21 (credit
 * digits 17/21 + credit-area labels 18..20).
 *
 * Build 0273: RETIRED.  Records 17..21 are now produced natively by
 * native_frontend_hud_emit (credit digit -> native credit block; labels 18..20
 * -> native .Lnq_title_labels set).  All eight callers are frontend HUD-setup
 * paths (arcade 0x3A20E/0x3A264/0x3A640/0x3A6C4/0x3A820/0x3A8E0, plus the now
 * retired 0x3B8B0/0x3B8EE); their records 17..21 are only ever rendered by the
 * frontend object-RAM scan (scene != 1), exactly where native_frontend_hud_emit
 * runs -- gameplay uses the separate .Lnq_gameplay HUD.  So this producer builds
 * no PC090OJ record; every live consumer has a native owner (consumer coverage
 * matrix in the build report).  A bare rts preserves all registers, matching the
 * caller contract. */
genesistan_pc090oj_hook_target_3b902:
    rts

/* RETIRED (setup/priority PC090OJ family).  This helper only PARKED/cleared
 * object-RAM records 5..13.  The producers that formerly populated that HUD
 * band (arcade builders 0x3B8B0 / 0x3B902, generic copier 0x3B930) are retired;
 * verified no live producer writes records 5..13 with content, so the clear
 * services nothing (records stay boot-blank).  Retired to a no-op (preserves
 * all registers). */
genesistan_pc090oj_hook_target_3b926:
    rts

/* PC090OJ final teardown: the Genesis compatibility hook for the generic
 * packed-byte -> object-RAM record copier (arcade 0x03B930) is REMOVED entirely
 * (hook symbol + its remap ownership), not left as an RTS shell.  Arcade 0x3B930
 * is unreachable -- its only callers are inert (0x3B902 body-replaced, 0x3B8B0
 * rts;nop) -- so its original bytes are left as dead, unreachable arcade code. */

/* The old Genesis fallback at these boundaries copied the gameplay player tuple
 * blocks regardless of which arcade producer was replaced.  Main-loop native
 * PLAYER_FRONT/BODY staging retires that player-only compatibility behavior;
 * gameplay keeps the established semantic dispatch/finalize ownership. */
genesistan_pc090oj_hook_target_41dae:
    cmpi.b  #PC090OJ_SCENE_GAMEPLAY_ID, genesistan_current_scene_id
    beq.s   .Lhook_41dae_gameplay_native
    rts
.Lhook_41dae_gameplay_native:
    move.w  0x02A2(%a5), %d0
    cmpi.w  #2, %d0
    beq.s   .Lhook_41dae_mode2
    bsr     native_stage_dispatch_41dae
    bra.s   .Lhook_41dae_finalize
.Lhook_41dae_mode2:
    bsr     native_stage_dispatch_45dfa
.Lhook_41dae_finalize:
    bsr     pc090oj_native_emit_pass
    rts

genesistan_pc090oj_hook_target_41f5e:
    cmpi.b  #PC090OJ_SCENE_GAMEPLAY_ID, genesistan_current_scene_id
    beq.s   .Lhook_41f5e_gameplay_native
    rts
.Lhook_41f5e_gameplay_native:
    bsr     native_sprite_frame_begin
    rts

genesistan_pc090oj_hook_target_45dfa:
    cmpi.b  #PC090OJ_SCENE_GAMEPLAY_ID, genesistan_current_scene_id
    beq.s   .Lhook_45dfa_gameplay_native
    rts
.Lhook_45dfa_gameplay_native:
    bsr     native_stage_dispatch_45dfa
    bsr     pc090oj_native_emit_pass
    rts


/* Build 0250 native gameplay sprite lanes.  These queues are semantic output
 * lanes, not PC090OJ object RAM: producers append visible 16x16 pieces and the
 * finalizer later concatenates them into one Genesis SAT chain.  Legacy mirror
 * code remains physically present for frontend/non-gameplay comparison only. */
native_sprite_frame_begin:
    /* arcade 0x5A098 publishes the persistent gameplay energy/status lane
     * before this frame boundary.  It owns refresh/retention of that lane;
     * clearing it here would discard the native status output before the
     * gameplay finalizer can consume it. */
    clr.w   native_front_effect_count
    clr.w   native_middle_count
    clr.w   native_back_enemy_count
    clr.w   pc090oj_sat_frame_ready
    rts

/* Main-loop player producers own these two completed semantic lanes.  Reset
 * once before arcade 0x51060 (FRONT), then BODY appends later at 0x5151C. */
native_player_frame_begin:
    clr.w   native_player_front_count
    clr.w   native_player_body_count
    rts

native_player_front_begin:
    move.w  #NATIVE_LANE_PLAYER_FRONT, native_sprite_lane
    rts

native_player_body_begin:
    move.w  #NATIVE_LANE_PLAYER_BODY, native_sprite_lane
    rts

/* Retained arcade expanders provide d1=word0, d6=Y, d3=code and d4=X.
 * Preserve their d2 loop counter while adapting to native_sprite_emit. */
native_player_piece:
    move.w  %d2, -(%sp)
    move.w  %d6, %d2
    bsr     native_sprite_emit
    move.w  (%sp)+, %d2
    rts

/* The old Block-A tuple-0 consumer copied this anchor into player state after
 * BODY generation.  Tuple 0 is the first iteration of the 0x545BA expander;
 * publish the same semantic coordinates directly without retaining Block A. */
native_player_body_anchor_piece:
    cmpi.w  #4, %d2
    bne.s   .Lnative_player_anchor_emit
    move.w  %d4, 0x129A(%a5)
    move.w  %d6, 0x129C(%a5)
.Lnative_player_anchor_emit:
    bra     native_player_piece

native_player_body_anchor_blank:
    cmpi.w  #4, %d2
    bne.s   .Lnative_player_anchor_blank_done
    clr.w   0x129A(%a5)
    clr.w   0x129C(%a5)
.Lnative_player_anchor_blank_done:
    rts

native_player_body_anchor_clear:
    clr.w   0x129A(%a5)
    clr.w   0x129C(%a5)
    rts

/* d1=word0/attr nibble+flip bits, d2=PC090OJ Y word, d3=source artwork code,
 * d4=PC090OJ X word, native_sprite_lane selects queue.  Preserves all caller
 * registers.  Hidden/blank/code-zero pieces append nothing.  All lanes retain
 * the producer's arcade-semantic Y; the shared visible-origin conversion is
 * applied once when the final SAT entry is encoded. */
native_sprite_emit:
    movem.l %d0-%d7/%a0-%a2, -(%sp)
    move.w  %d3, %d0
    andi.w  #0x1FFF, %d0
    beq     .Lnse_done
    cmpi.w  #0x00FF, %d0
    beq     .Lnse_done
    move.w  %d2, %d0
    andi.w  #0x01FF, %d0
    cmpi.w  #0x0180, %d0
    beq     .Lnse_done

    move.w  native_sprite_lane, %d0
    cmpi.w  #NATIVE_LANE_HUD, %d0
    beq.s   .Lnse_hud
    cmpi.w  #NATIVE_LANE_FRONT_EFFECT, %d0
    beq.s   .Lnse_front_effect
    cmpi.w  #NATIVE_LANE_PLAYER_FRONT, %d0
    beq.s   .Lnse_player_front
    cmpi.w  #NATIVE_LANE_MIDDLE, %d0
    beq.s   .Lnse_middle
    cmpi.w  #NATIVE_LANE_PLAYER_BODY, %d0
    beq.s   .Lnse_player_body
    cmpi.w  #NATIVE_LANE_BACK_ENEMY, %d0
    beq.s   .Lnse_back_enemy
    bra     .Lnse_done
.Lnse_hud:
    lea     native_queue_hud, %a0
    lea     native_hud_count, %a1
    move.w  #NATIVE_HUD_BOUND, %d5
    bra.s   .Lnse_store
.Lnse_front_effect:
    lea     native_queue_front_effect, %a0
    lea     native_front_effect_count, %a1
    move.w  #NATIVE_FRONT_EFFECT_BOUND, %d5
    bra.s   .Lnse_store
.Lnse_player_front:
    lea     native_queue_player_front, %a0
    lea     native_player_front_count, %a1
    move.w  #NATIVE_PLAYER_FRONT_BOUND, %d5
    bra.s   .Lnse_store
.Lnse_middle:
    lea     native_queue_middle, %a0
    lea     native_middle_count, %a1
    move.w  #NATIVE_MIDDLE_BOUND, %d5
    bra.s   .Lnse_store
.Lnse_player_body:
    lea     native_queue_player_body, %a0
    lea     native_player_body_count, %a1
    move.w  #NATIVE_PLAYER_BODY_BOUND, %d5
    bra.s   .Lnse_store
.Lnse_back_enemy:
    lea     native_queue_back_enemy, %a0
    lea     native_back_enemy_count, %a1
    move.w  #NATIVE_BACK_ENEMY_BOUND, %d5
.Lnse_store:
    move.w  (%a1), %d0
    cmp.w   %d5, %d0
    bhs.s   .Lnse_done
    move.w  %d0, %d6
    lsl.w   #3, %d6
    adda.w  %d6, %a0
    move.w  %d1, (%a0)+
    move.w  %d2, (%a0)+
    move.w  %d3, (%a0)+
    move.w  %d4, (%a0)+
    addq.w  #1, (%a1)
.Lnse_done:
    movem.l (%sp)+, %d0-%d7/%a0-%a2
    rts

native_stage_dispatch_41dae:
    movem.l %d0-%d7/%a0-%a6, -(%sp)
    move.w  #NATIVE_LANE_PLAYER_FRONT, native_sprite_lane
    lea     0x0508(%a5), %a4
    lea     0x00D001C8, %a1
    moveq   #(2 - 1), %d5
.Lns41_players1:
    moveq   #13, %d2
    bsr     .Lnative_emit_actor_common
    adda.w  #64, %a4
    dbra    %d5, .Lns41_players1

    move.w  #NATIVE_LANE_MIDDLE, native_sprite_lane
    lea     0x05C8(%a5), %a4
    lea     0x00D00300, %a1
    moveq   #(6 - 1), %d5
.Lns41_middle:
    moveq   #4, %d2
    bsr     .Lnative_emit_actor_common
    adda.w  #64, %a4
    dbra    %d5, .Lns41_middle

    move.w  #NATIVE_LANE_BACK_ENEMY, native_sprite_lane
    lea     0x02C8(%a5), %a4
    lea     0x00D00460, %a1
    moveq   #0, %d5
.Lns41_enemy:
    moveq   #10, %d2
    cmpi.w  #8, %d5
    bne.s   .Lns41_enemy_count_ok
    moveq   #19, %d2
.Lns41_enemy_count_ok:
    tst.b   5(%a4)
    beq.s   .Lnative_actor_advance_only_41_enemy
    tst.b   3(%a4)
    bne.s   .Lnative_actor_advance_only_41_enemy
    bsr     .Lnative_emit_actor_common
    bra.s   .Lns41_enemy_next
.Lnative_actor_advance_only_41_enemy:
    move.w  %d2, %d0
    lsl.w   #3, %d0
    adda.w  %d0, %a1
.Lns41_enemy_next:
    adda.w  #64, %a4
    addq.w  #1, %d5
    cmpi.w  #9, %d5
    blo.s   .Lns41_enemy

    move.w  #NATIVE_LANE_FRONT_EFFECT, native_sprite_lane
    lea     0x0748(%a5), %a4
    lea     0x00D00170, %a1
    moveq   #(11 - 1), %d5
.Lns41_effect:
    moveq   #1, %d2
    tst.b   0x36(%a4)
    bne.s   .Lnative_actor_advance_only_41_effect
    bsr     .Lnative_emit_actor_common
    bra.s   .Lns41_effect_next
.Lnative_actor_advance_only_41_effect:
    adda.w  #8, %a1
.Lns41_effect_next:
    adda.w  #64, %a4
    dbra    %d5, .Lns41_effect
    movem.l (%sp)+, %d0-%d7/%a0-%a6
    rts

native_stage_dispatch_45dfa:
    movem.l %d0-%d7/%a0-%a6, -(%sp)
    move.w  #NATIVE_LANE_BACK_ENEMY, native_sprite_lane
    lea     0x05C8(%a5), %a4
    lea     0x00D00460, %a1
    moveq   #(6 - 1), %d5
.Lns45_enemy:
    moveq   #10, %d2
    cmpi.w  #2, 0x0214(%a5)
    bls.s   .Lns45_enemy_count_ok
    moveq   #20, %d2
.Lns45_enemy_count_ok:
    bsr     .Lnative_emit_actor_common
    adda.w  #64, %a4
    dbra    %d5, .Lns45_enemy

    move.w  #NATIVE_LANE_FRONT_EFFECT, native_sprite_lane
    lea     0x0748(%a5), %a4
    lea     0x00D00170, %a1
    moveq   #(6 - 1), %d5
.Lns45_effect:
    moveq   #6, %d2
    bsr     .Lnative_emit_actor_common
    adda.w  #64, %a4
    dbra    %d5, .Lns45_effect

    move.w  #NATIVE_LANE_MIDDLE, native_sprite_lane
    lea     0x08C8(%a5), %a4
    lea     0x00D00300, %a1
    moveq   #(5 - 1), %d5
.Lns45_middle:
    moveq   #4, %d2
    bsr     .Lnative_emit_actor_common
    adda.w  #64, %a4
    dbra    %d5, .Lns45_middle
    movem.l (%sp)+, %d0-%d7/%a0-%a6
    rts

/* A4=actor, D2=piece budget for this actor.  native_sprite_lane (set by the
 * caller) selects the destination semantic lane.
 *
 * Build 0260: DIRECT-NATIVE gameplay sprite production.  Build 0259's bridge --
 * which ran the relocated arcade record-expander (0x3D254) into an eight-byte
 * PC090OJ-format scratch tuple and decoded it back -- is removed.  This routine
 * reproduces the arcade actor->piece expansion directly from the arcade
 * semantic state and emits each 16x16 piece straight into the native semantic
 * lane, with NO PC090OJ record, NO 0xD00000, NO Y=0x180 park record, NO scratch
 * tuple, and NO pack-then-decode.
 *
 * Provenance (original-arcade MAME attract-demo trace,
 * states/traces/direct_native_sprite_provenance_*): 100% of Stage-1 gameplay
 * actors dispatch to the DEFAULT expander (0x3C950, descriptor type nibble
 * 0x00); zero specialized-type actor-frames were observed.  The default
 * expander's per-piece fields are all live actor/mapping state:
 *   attr@0  = (per-piece type 0x80 ? flipX 0x4000 : 0) | (a4@39 if bit6 set)
 *   Y       = sext(mapY) + a4@26  (+ a4@24 when per-piece type 0x70)
 *   code    = a4@30 + (flip ? -mapCode : mapCode)   [read directly, no record]
 *   X       = sext(mapX) + a4@22   (facing==0 -> mirror: a4@22 - mapX - 0x10)
 * per-piece mapping stream = [control, Ybyte, codebyte, Xbyte]; control 0xFF is
 * a 1-byte blank/park (emit nothing).  a4@2==0 selects the mirrored orientation
 * (arcade 0x3C9A6).  a0 = family_descriptor = reloc_table_base +
 * u16[reloc_table_base + class*2]. */
.Lnative_emit_actor_common:
    movem.l %d0-%d7/%a0-%a6, -(%sp)
    tst.b   0(%a4)                     /* active */
    beq     .Lnea_ret
    tst.b   1(%a4)                     /* class nonzero */
    beq     .Lnea_ret
    andi.l  #0x0000FFFF, %d2
    beq     .Lnea_ret
    move.w  %d2, %d5                    /* d5 = piece budget (loop count) */

    /* a0 = family descriptor (relocated arcade family tables, +0x200 copy) */
    moveq   #0, %d1
    move.b  0x38(%a4), %d1             /* family a4@0x38 */
    cmpi.w  #4, %d1
    bhi     .Lnea_ret
    lsl.w   #2, %d1
    lea     .Lnea_fam_bases, %a1
    movea.l (%a1,%d1.w), %a1           /* a1 = reloc table base */
    moveq   #0, %d0
    move.b  1(%a4), %d0               /* class a4@1 */
    add.w   %d0, %d0
    move.w  (%a1,%d0.w), %d0          /* u16 self-relative descriptor offset */
    lea     (%a1,%d0.w), %a0          /* a0 = descriptor / piece stream */

    move.b  (%a0), %d3                 /* dispatcher type nibble */
    andi.b  #0xF0, %d3
    beq.s   .Lnea_default              /* 0x00 */
    cmpi.b  #0x40, %d3
    beq.s   .Lnea_default
    cmpi.b  #0x70, %d3
    beq.s   .Lnea_default
    cmpi.b  #0x80, %d3
    beq.s   .Lnea_default
    cmpi.b  #0xD0, %d3
    beq.s   .Lnea_default
    cmpi.b  #0xE0, %d3
    beq.s   .Lnea_default
    cmpi.b  #0xF0, %d3
    beq.s   .Lnea_default
    bra     .Lnea_special              /* one of the 8 specialized dispatch types */

.Lnea_default:
    tst.b   2(%a4)                     /* facing a4@2 */
    beq     .Lnea_dmirror

.Lnea_dloop:                            /* --- normal orientation (arcade 0x3C960) --- */
    moveq   #0, %d0
    move.b  (%a0)+, %d0               /* control byte */
    cmpi.b  #0xFF, %d0
    beq.s   .Lnea_dnext               /* blank/park -> emit nothing */
    move.b  %d0, %d3
    andi.b  #0xF0, %d3                /* per-piece type nibble */
    moveq   #0, %d7                    /* flip flag */
    cmpi.b  #0x40, %d3
    bne.s   .Lnea_d_nf
    moveq   #1, %d7
.Lnea_d_nf:
    moveq   #0, %d1                    /* attr */
    cmpi.b  #0x80, %d3
    bne.s   .Lnea_d_na
    ori.w   #0x4000, %d1
.Lnea_d_na:
    btst    #6, 0x27(%a4)             /* a4@39 visibility */
    beq.s   .Lnea_d_av
    move.b  0x27(%a4), %d1            /* attr low byte = a4@39 */
.Lnea_d_av:
    moveq   #0, %d2                    /* Y */
    move.b  (%a0)+, %d2
    ext.w   %d2
    add.w   0x1a(%a4), %d2            /* + base Y a4@26 */
    cmpi.b  #0x70, %d3
    bne.s   .Lnea_d_ny
    add.w   0x18(%a4), %d2           /* type 0x70: + a4@24 */
.Lnea_d_ny:
    moveq   #0, %d0                    /* code */
    move.b  (%a0)+, %d0
    tst.w   %d7
    beq.s   .Lnea_d_nc
    neg.w   %d0
.Lnea_d_nc:
    add.w   0x1e(%a4), %d0           /* + base tile a4@30 */
    move.w  %d0, %d3
    moveq   #0, %d4                    /* X */
    move.b  (%a0)+, %d4
    ext.w   %d4
    add.w   0x16(%a4), %d4           /* + base X a4@22 */
    bsr     native_sprite_emit
.Lnea_dnext:
    subq.w  #1, %d5
    bne     .Lnea_dloop
    bra     .Lnea_ret

.Lnea_dmirror:                          /* --- mirrored orientation (arcade 0x3C9A6) --- */
    moveq   #0, %d0
    move.b  (%a0)+, %d0
    cmpi.b  #0xFF, %d0
    beq.s   .Lnea_mnext
    move.b  %d0, %d3
    andi.b  #0xF0, %d3
    moveq   #0, %d7
    cmpi.b  #0x40, %d3
    bne.s   .Lnea_m_nf
    moveq   #1, %d7
.Lnea_m_nf:
    move.w  #0x4000, %d1              /* mirror path always sets flipX */
    btst    #6, 0x27(%a4)
    beq.s   .Lnea_m_av
    move.b  0x27(%a4), %d1
.Lnea_m_av:
    moveq   #0, %d2
    move.b  (%a0)+, %d2
    ext.w   %d2
    add.w   0x1a(%a4), %d2           /* Y = sext(byte) + a4@26 (no 0x70 adjust) */
    moveq   #0, %d0
    move.b  (%a0)+, %d0
    tst.w   %d7
    beq.s   .Lnea_m_nc
    neg.w   %d0
.Lnea_m_nc:
    add.w   0x1e(%a4), %d0
    move.w  %d0, %d3
    moveq   #0, %d4
    move.b  (%a0)+, %d4
    ext.w   %d4
    neg.w   %d4
    subi.w  #0x10, %d4
    add.w   0x16(%a4), %d4           /* X = a4@22 - sext(byte) - 0x10 */
    bsr     native_sprite_emit
.Lnea_mnext:
    subq.w  #1, %d5
    bne     .Lnea_dmirror
    bra     .Lnea_ret

/* Specialized dispatch types (0x10/0x20/0x30/0x50/0x60/0x90/0xA0/0xB0/0xC0).
 * Original-arcade trace shows ZERO specialized-type actor-frames in Stage-1
 * gameplay, so this path is not exercised by observed gameplay; it is kept
 * native and record-free for completeness.  Every specialized handler begins by
 * dereferencing the frame-indexed piece pointer (movea.l a0@(2)); each piece is
 * a position delta with retained artwork, so code is sourced from the actor base
 * tile a4@30 and attribute from a4@39 -- no PC090OJ record, no scratch. */
.Lnea_special:
    movea.l 2(%a0), %a0              /* piece data pointer (shared by all 8) */
    moveq   #0, %d0
    move.b  0x0b(%a4), %d0          /* animation frame a4@0x0B */
    add.w   %d0, %d0
    move.w  %d0, %d1
    add.w   %d0, %d0
    add.w   %d1, %d0               /* frame*3 */
    adda.w  %d0, %a0
.Lnea_sloop:
    moveq   #0, %d0
    move.b  (%a0)+, %d0
    cmpi.b  #0xFF, %d0
    beq.s   .Lnea_snext
    ext.w   %d0
    move.w  0x1a(%a4), %d2         /* Y = base Y + delta */
    add.w   %d0, %d2
    move.w  0x1e(%a4), %d3         /* code = base tile a4@30 (retained) */
    move.w  0x16(%a4), %d4         /* X = base X a4@22 */
    moveq   #0, %d1
    move.b  0x27(%a4), %d1         /* attr = a4@39 */
    bsr     native_sprite_emit
.Lnea_snext:
    subq.w  #1, %d5
    bne     .Lnea_sloop
.Lnea_ret:
    movem.l (%sp)+, %d0-%d7/%a0-%a6
    rts

    .align 2
/* Relocated arcade family descriptor-table bases (arcade base + 0x200 copy):
 * fam0 0x3D09E, fam1 0x4771C, fam2 0x3F0CE, fam3 0x40004, fam4 0x4002C. */
.Lnea_fam_bases:
    .long 0x0003D29E
    .long 0x0004791C
    .long 0x0003F2CE
    .long 0x00040204
    .long 0x0004022C

    .align 2



/* RETIRED (setup/priority PC090OJ family).  This helper only PARKED/cleared
 * object-RAM records 9..16 (its retired PLAYER_FRONT a5+0x170 tuple rebuild was
 * already absent; PLAYER_FRONT is main-loop native staging).  Verified no live
 * producer writes records 9..16 with content, so the clear services nothing
 * (records stay boot-blank).  Retired to a no-op (preserves all registers). */
genesistan_pc090oj_hook_target_59f5e:
    rts

/* PC090OJ ctrl register (word offset 0x0DFF / HW 0x00D01BFE).
 * Bit 0 is the global-flip control (a change flips every sprite on/off screen),
 * so an actual change reevaluates all 256 records by requesting a full
 * candidate sweep processed at the next VBlank (§9-E.4).
 */
genesistan_pc090oj_ctrl_set_1:
    cmpi.w  #1, pc090oj_ctrl_shadow
    beq.s   .Lctrl_set_1_done
    move.w  #1, pc090oj_ctrl_shadow
.Lctrl_set_1_done:
    rts

genesistan_pc090oj_ctrl_set_0:
    tst.w   pc090oj_ctrl_shadow
    beq.s   .Lctrl_set_0_done
    clr.w   pc090oj_ctrl_shadow
.Lctrl_set_0_done:
    rts

/* External sprite_ctrl at HW 0x00380000.  D0 holds the arcade value; its colour
 * bank feeds sprite palette selection.  On an actual change, reevaluate (a full
 * sweep is a safe superset of the represented-only palette refresh).
 */
genesistan_pc090oj_sprite_ctrl_write_d0:
    cmp.w   pc090oj_sprite_ctrl_shadow, %d0
    beq.s   .Lsprite_ctrl_write_done
    move.w  %d0, pc090oj_sprite_ctrl_shadow
.Lsprite_ctrl_write_done:
    rts

genesistan_pc090oj_sprite_ctrl_clear:
    tst.w   pc090oj_sprite_ctrl_shadow
    beq.s   .Lsprite_ctrl_clear_done
    clr.w   pc090oj_sprite_ctrl_shadow
.Lsprite_ctrl_clear_done:
    rts

genesistan_hook_3ad44_dispatch:
    movem.l %d0-%d7/%a0-%a6, -(%sp)

    /* A0 dispatch: PC080SN C-range ONLY -> [0x00C00000,0x00C10000).
     * The PC090OJ D-range (0x00D00000..0x00D007FF) is fully retired: its only
     * callers were the arcade object-RAM clear routines 0x03AD4C / 0x03AD72,
     * which are now RTS (their whole body was obsolete PC090OJ record clearing
     * with no native effect), so no D-range address ever reaches this
     * dispatcher.  No PC090OJ recognition remains here.  This dispatcher now
     * survives ONLY for its still-live PC080SN C-range callers (0x03AE70/80,
     * 0x03AF38/48) and is scheduled for deletion once PC080SN C-range ownership
     * is native (see the PC080SN Final-Retirement Handoff). */
    move.l  %a0, %d2
    cmpi.l  #0x00C00000, %d2
    blo     .Lhook_3ad44_audit
    cmpi.l  #0x00C10000, %d2
    bhs     .Lhook_3ad44_audit

.Lhook_3ad44_tilemap:
    cmpi.l  #0x00C04000, %d2
    blo.s   .Lhook_3ad44_bg_names
    cmpi.l  #0x00C08000, %d2
    blo.s   .Lhook_3ad44_bg_scroll
    cmpi.l  #0x00C0C000, %d2
    blo.s   .Lhook_3ad44_fg_names
    bsr     genesistan_hook_pc080sn_fg_scroll_fill
    bra     .Lhook_3ad44_finish

.Lhook_3ad44_bg_names:
    bsr     genesistan_hook_tilemap_bg_fill
    bra     .Lhook_3ad44_finish

.Lhook_3ad44_bg_scroll:
    bsr     genesistan_hook_pc080sn_bg_scroll_fill
    bra     .Lhook_3ad44_finish

.Lhook_3ad44_fg_names:
    bsr     genesistan_hook_tilemap_fg_fill
    bra     .Lhook_3ad44_finish

.Lhook_3ad44_audit:
    /* Reuse §7.3 audit-guard capture + heartbeat halt loop. */
    move.l  60(%sp), %d0
    move.l  %d0, audit_guard_caller_pc

    lea     audit_guard_register_snapshot, %a1
    moveq   #(15 - 1), %d0
.Lhook_3ad44_snap:
    move.l  (%sp,%d0.w*4), %d1
    move.l  %d1, (%a1)+
    dbra    %d0, .Lhook_3ad44_snap

    move.w  0x00C00008, audit_guard_vcount
    move.w  #0x3AD4, audit_guard_fired_flag
    bra     .Lag_halt_loop

.Lhook_3ad44_finish:
    movem.l (%sp)+, %d0-%d7/%a0-%a6
    rts

/* RETIRED (setup/priority PC090OJ family).  This helper only initialized
 * object-RAM records 76..79 with code=0 (blank / not-drawable) at off-screen
 * X=0x160: zero visible semantic output.  The former priority/flip "ladder"
 * intent is already owned by the native lane ORDER (gameplay emits lanes in
 * priority order); no ordering is lost.  Verified no producer writes records
 * 76..79 with nonzero code, so they stay boot-blank without this emit.  Retired
 * to a no-op (preserves all registers). */
genesistan_pc090oj_hook_init_priority_3ad84:
    rts

genesistan_pc090oj_hook_score_digit_3b802:
    /* Build 0270: RETIRED.  All 0x3B802 consumers are now produced natively by
     * the native_frontend_hud_emit subsystem (Build 0272): player/high scores +
     * credit-line digits for the title and every other frontend scene, and the
     * gameplay project_p1_hud path.  That subsystem also retires the stale
     * PC090OJ digit records (code-gated), so the frontend scanner no longer
     * carries any record-number HUD skip.  Every live consumer has a native
     * owner (consumer coverage matrix in the build report). */
    rts

/* RETIRED (setup/priority PC090OJ family).  This helper only initialized
 * object-RAM records 72..75 with code=0 (blank / not-drawable): zero visible
 * semantic output, and PLAYER_BODY is main-loop native staging.  Verified no
 * producer writes records 72..75 with nonzero code, so the records stay
 * boot-blank without this emit.  Retired to a no-op (preserves all registers).
 * See docs/design/Andy_5a502_ownership_setup_priority_native_conversion.md. */
genesistan_pc090oj_hook_slot_init_54052:
    rts

/* arcade_pc 0x054810: final native realization of the player-attached
 * damage/impact auxiliary selected by the retained 0x0547C0 state machine.
 * a0 points at the selected four-piece source frame.  Historical PC090OJ
 * records 44..47 and their hardware-slot identity are deliberately absent. */
genesistan_pc090oj_hook_player_aux_native_54810:
    movem.l %d0-%d7/%a0-%a6, -(%sp)

    move.w  #NATIVE_LANE_FRONT_EFFECT, native_sprite_lane
    moveq   #4, %d7
.Lplayer_aux_native_loop:
    move.w  4(%a0), %d1

    moveq   #0, %d2
    move.b  3(%a0), %d2
    ext.w   %d2
    add.w   0x129C(%a5), %d2
    addq.w  #1, %d2
    andi.w  #0x01FF, %d2

    move.w  (%a0), %d3

    moveq   #0, %d4
    move.b  2(%a0), %d4
    ext.w   %d4
    add.w   0x129A(%a5), %d4
    andi.w  #0x01FF, %d4

    bsr     native_sprite_emit

    adda.w  #6, %a0
    subq.w  #1, %d7
    bne.s   .Lplayer_aux_native_loop

    movem.l (%sp)+, %d0-%d7/%a0-%a6
    rts

/* Frontend-direct conversion of the transient item decay.  The arcade routine
 * (throttled to every 4th frame via a5@0x1392&3) uniformly decremented every
 * item record's Y by 1 and blanked a record once its Y reached 16 -- i.e. the
 * whole set scrolls up and each item vanishes at Y<=16.  Since the decrement is
 * uniform, that per-record mutation is exactly one accumulated scroll offset,
 * which .Lnq_transient_items_emit applies (Y' = Y - scroll; drop at Y'<=16).
 * The two arcade side-effect clears (a5@0x10AE / a5@0x10B0) are preserved
 * verbatim.  No object-RAM / staged-descriptor mutation. */
genesistan_pc090oj_hook_sprite_decay_5607c:
    move.w  0x1392(%a5), %d0
    andi.w  #0x0003, %d0
    bne.s   .Lhook_5607c_done

    clr.w   0x10AE(%a5)
    clr.w   0x10B0(%a5)

    /* Restore the item-page TEXT-plane vertical scroll that the Build0286
     * conversion dropped.  Arcade 0x5607C decremented the 9-bit counter
     * a5@0x10EE and called 0x55AB4; that routine (rewritten by the spec) writes
     * a5@0x10EE -> staged_scroll_y_bg, i.e. the BG (Plane B) text-plane VSRAM
     * scroll that vdp_commit_scroll commits every VBlank.  Without it the item
     * description text stayed static while the sprites scrolled.  This advances
     * at the same 1-unit-per-decay cadence as transient_items_scroll below, so
     * text and sprites move together exactly as in the arcade. */
    move.w  0x10EE(%a5), %d1
    subq.w  #1, %d1
    andi.w  #0x01FF, %d1
    move.w  %d1, 0x10EE(%a5)
    jsr     (0x00055CB4).l          /* arcade_pc 0x055AB4 (+0x200 blind; postpatch relocates shift-aware to staged_scroll writer) */

    tst.w   transient_items_active
    beq.s   .Lhook_5607c_done
    addq.w  #1, transient_items_scroll

.Lhook_5607c_done:
    rts

/* Frontend-direct conversion (was: copy the ROM tuple stream into PC090OJ
 * object RAM).  The arcade caller passes a0 = the selected ROM tuple stream
 * (0x56226 = 17 treasure/item tuples, or 0x562B0 = 3), already resolved to its
 * runtime address by the shift-aware relocation of the caller's movea.l.  We
 * latch that live pointer, mark the family active, and reset the scroll; the
 * frontend emitter (.Lnq_transient_items_emit) walks the stream directly into
 * the native SAT.  No object-RAM write, no slot ownership. */
genesistan_pc090oj_hook_copy_56114:
    move.l  %a0, transient_items_source_ptr
    move.w  #1, transient_items_active
    clr.w   transient_items_scroll
    rts

/* Frontend-direct retirement (was: park the item object-RAM records).  The
 * arcade clear is the semantic end-of-life for the transient item family, so we
 * retire the native semantic state; the emitter then contributes no pieces. */
genesistan_pc090oj_hook_zero_fill_56440:
    clr.w   transient_items_active
    rts

genesistan_pc090oj_hook_status_sprite_5a098:
    /* Direct-native gameplay energy/status producer.  Preserve the original
     * arcade semantic state machine and publish its eight ordered visible-piece
     * positions directly into the native HUD lane.  The old PC090OJ destination
     * (HW 0xD00048), eight-byte records, virtual records 30..43 and
     * .Lpc090oj_emit_slot are not part of this path.  The queue is persistent:
     * original 0x5100A can skip this producer, and the arcade records likewise
     * retained their previous semantic output on those frames. */
    movem.l %d0-%d7/%a0-%a6, -(%sp)
    move.w  #8, native_hud_count

    move.w  0x013A(%a5), %d0             /* current energy, high byte = units */
    btst    #15, %d0
    beq.s   .Lstatus_energy_valid
    clr.w   0x013A(%a5)                   /* original invalid-energy recovery */
.Lstatus_energy_valid:
    move.w  #0x00E8, %d2                 /* semantic PC090OJ Y */
    move.w  #0x0010, %d4                 /* first semantic X */

    /* Preserve the original animated leading status piece decision. */
    move.w  0x013A(%a5), %d0
    lsr.w   #8, %d0
    lsr.w   #3, %d0
    andi.w  #0x0007, %d0
    ori.w   #0x0008, %d0
    move.w  %d0, 0x12A6(%a5)
    addi.w  #0x0010, 0x12A4(%a5)
    move.w  0x12A4(%a5), %d1
    move.w  0x12A6(%a5), %d5
    move.w  0x1306(%a5), %d6
    cmpi.w  #0x000C, %d5
    ble.s   .Lstatus_selector_clamped
    moveq   #0x0C, %d5
.Lstatus_selector_clamped:
    subq.w  #2, %d5
    btst    #0, %d6
    bne.s   .Lstatus_selector_odd
    btst    %d5, %d1
    bne.s   .Lstatus_indicator_done
    bra.s   .Lstatus_indicator_update
.Lstatus_selector_odd:
    btst    %d5, %d1
    beq.s   .Lstatus_indicator_done
.Lstatus_indicator_update:
    move.w  0x130A(%a5), %d7
    addi.w  #0x0010, 0x130A(%a5)
    moveq   #7, %d0
    cmpi.w  #7, %d5
    bge.s   .Lstatus_indicator_bit_ready
    subq.w  #1, %d0
.Lstatus_indicator_bit_ready:
    move.w  #0x03CA, %d3
    btst    %d0, %d7
    beq.s   .Lstatus_indicator_code_ready
    addq.w  #1, %d3
.Lstatus_indicator_code_ready:
    btst    %d0, %d7
    bne.s   .Lstatus_indicator_counter_done
    addq.w  #1, 0x1306(%a5)
.Lstatus_indicator_counter_done:
    moveq   #0, %d1                     /* original word0: no local flip/bank */
    moveq   #0, %d0                     /* semantic output index 0 */
    bsr     .Lstatus_store_piece
.Lstatus_indicator_done:
    addi.w  #0x0010, %d4

    /* 0x12FC==1 is the arcade refresh gate.  Otherwise retain the last native
     * semantic bar, exactly as the original records remained untouched. */
    cmpi.w  #1, 0x12FC(%a5)
    bne     .Lstatus_low_energy_blink

    moveq   #0, %d1
    move.w  #0x03CC, %d3                 /* left cap */
    moveq   #1, %d0
    bsr     .Lstatus_store_piece
    addi.w  #0x0010, %d4

    move.w  0x013A(%a5), %d0
    lsr.w   #8, %d0
    cmpi.w  #0x0030, %d0
    blo.s   .Lstatus_energy_clamped
    move.w  #0x0030, %d0
.Lstatus_energy_clamped:
    move.w  %d0, %d1
    andi.w  #0xFFF8, %d0
    lsr.w   #3, %d0                     /* d0 = full cells (0..6) */
    andi.w  #0x0007, %d1                /* d1 = partial-cell units */
    move.w  %d0, %d5
    moveq   #6, %d6                     /* six semantic energy cells */
    moveq   #2, %d7                     /* first cell output index */
    move.w  %d1, -(%sp)                 /* preserve partial units across emits */
    move.w  #0x00FF, 0x1328(%a5)
    tst.w   %d5
    bne.s   .Lstatus_full_loop_test
    move.w  #1, 0x1328(%a5)

.Lstatus_full_loop_test:
    tst.w   %d5
    beq.s   .Lstatus_partial
.Lstatus_full_loop:
    move.w  #0x03CD, %d3
    move.w  %d7, %d0
    moveq   #0, %d1
    bsr     .Lstatus_store_piece
    addi.w  #0x0010, %d4
    addq.w  #1, %d7
    subq.w  #1, %d6
    subq.w  #1, %d5
    bne.s   .Lstatus_full_loop

.Lstatus_partial:
    move.w  (%sp)+, %d1
    tst.w   %d1
    beq.s   .Lstatus_no_partial
    add.w   %d1, %d1
    lea     .Lstatus_partial_codes, %a1
    move.w  0(%a1,%d1.w), %d3
    move.w  %d3, 0x132A(%a5)
    move.w  %d7, %d0
    moveq   #0, %d1
    bsr     .Lstatus_store_piece
    addi.w  #0x0010, %d4
    addq.w  #1, %d7
    subq.w  #1, %d6
    bra.s   .Lstatus_empty_test
.Lstatus_no_partial:
    move.w  #0x03D5, 0x132A(%a5)

.Lstatus_empty_test:
    tst.w   %d6
    beq.s   .Lstatus_low_energy_blink
.Lstatus_empty_loop:
    move.w  #0x03D5, %d3
    move.w  %d7, %d0
    moveq   #0, %d1
    bsr     .Lstatus_store_piece
    addi.w  #0x0010, %d4
    addq.w  #1, %d7
    subq.w  #1, %d6
    bne.s   .Lstatus_empty_loop

.Lstatus_low_energy_blink:
    cmpi.w  #1, 0x1328(%a5)
    bne.s   .Lstatus_update_lifecycle
    move.w  0x1308(%a5), %d0
    lsr.w   #1, %d0
    btst    #0, %d0
    beq.s   .Lstatus_blink_empty
    move.w  0x132A(%a5), %d0
    bra.s   .Lstatus_blink_store
.Lstatus_blink_empty:
    move.w  #0x03D5, %d0
.Lstatus_blink_store:
    lea     native_queue_hud, %a0
    move.w  %d0, (2 * NATIVE_QUEUE_ENTRY_BYTES + 4)(%a0)

.Lstatus_update_lifecycle:
    /* Inline original helper 0x5A244: publish low/normal-energy transitions. */
    cmpi.w  #1, 0x1328(%a5)
    bne.s   .Lstatus_lifecycle_normal
    cmpi.w  #0x00FF, 0x13CE(%a5)
    beq.s   .Lstatus_lifecycle_low_steady
    move.w  #1, 0x13D2(%a5)
    bra.s   .Lstatus_lifecycle_low_commit
.Lstatus_lifecycle_low_steady:
    move.w  #0x0011, 0x13D2(%a5)
.Lstatus_lifecycle_low_commit:
    move.w  #1, 0x13CE(%a5)
    bra.s   .Lstatus_sound
.Lstatus_lifecycle_normal:
    cmpi.w  #1, 0x13CE(%a5)
    beq.s   .Lstatus_lifecycle_normal_steady
    move.w  #0x00FF, 0x13D2(%a5)
    bra.s   .Lstatus_lifecycle_normal_commit
.Lstatus_lifecycle_normal_steady:
    move.w  #0x00FE, 0x13D2(%a5)
.Lstatus_lifecycle_normal_commit:
    move.w  #0x00FF, 0x13CE(%a5)

.Lstatus_sound:
    cmpi.w  #0, 0x12F4(%a5)
    bne.s   .Lstatus_sound_recovery
    cmpi.w  #0x0011, 0x13D2(%a5)
    bne.s   .Lstatus_sound_recovery
    moveq   #6, %d0
    jsr     (0x0003A2EC).l               /* address_map: arcade_pc 0x03A0EC */
    bra.s   .Lstatus_done
.Lstatus_sound_recovery:
    cmpi.w  #0x00FE, 0x13D2(%a5)
    bne.s   .Lstatus_done
    move.w  #0x0029, %d0
    jsr     (0x0003A316).l               /* address_map: arcade_pc 0x03A116 */

.Lstatus_done:
    movem.l (%sp)+, %d0-%d7/%a0-%a6
    rts

/* d0=native semantic output index, d1=attr, d2=Y, d3=code, d4=X.  This is the
 * final native queue shape consumed directly by .Lnq_emit_lane, not a PC090OJ
 * record and not input to any compatibility scanner or decoder. */
.Lstatus_store_piece:
    movem.l %d0/%a0, -(%sp)
    lsl.w   #3, %d0
    lea     native_queue_hud, %a0
    adda.w  %d0, %a0
    move.w  %d1, (%a0)+
    move.w  %d2, (%a0)+
    move.w  %d3, (%a0)+
    move.w  %d4, (%a0)+
    movem.l (%sp)+, %d0/%a0
    rts

.Lstatus_partial_codes:
    .word 0x03D5, 0x03D4, 0x03D3, 0x03D2
    .word 0x03D1, 0x03D0, 0x03CF, 0x03CE

genesistan_pc090oj_hook_audit_guard:
    movem.l %d0-%d7/%a0-%a6, -(%sp)

    /* return address for invoking site */
    move.l  60(%sp), %d0
    move.l  %d0, audit_guard_caller_pc

    /* snapshot registers (d0-d7,a0-a6 = 15 longs) */
    lea     audit_guard_register_snapshot, %a1
    moveq   #(15 - 1), %d0
.Lag_snap:
    move.l  (%sp,%d0.w*4), %d1
    move.l  %d1, (%a1)+
    dbra    %d0, .Lag_snap

    move.w  0x00C00008, audit_guard_vcount
    move.w  #0x510E, audit_guard_fired_flag

.Lag_halt_loop:
    move.b  audit_guard_heartbeat, %d0
    addq.b  #1, %d0
    move.b  %d0, audit_guard_heartbeat
    bra     .Lag_halt_loop

/* ------------------------------------------------------------------------- */
/* VBlank sprite prepare / commit split                                      */

/* ========================================================================= */
/* N1 native sprite pipeline (Build 0219): object table -> shadow SAT.       */
/*                                                                           */
/* The 256-row object table (pc090oj_object_ram) is the arcade program's own */
/* persistent slot-addressed sprite store: incremental producers (score,     */
/* status, decay, copy hooks) update rows in place exactly as arcade code    */
/* updated PC090OJ RAM.  Once per frame ONE ascending pass emits final       */
/* Genesis SAT entries into a double-buffered shadow SAT.  Ascending row     */
/* order = PC090OJ paint priority (MAME pc090oj draws descending, so record  */
/* 0 lands on top; Genesis link order gives the same result).  Retirement is */
/* implicit: rows the producers cleared/blanked simply emit nothing.         */
/* No mirror shadow, no candidates, no representation/eviction engine, no   */
/* record->slot map, no VBlank record scans in gameplay (the pass runs at    */
/* the end of the arcade's own sprite dispatcher; frontend scenes fall back  */
/* to a VBlank pass). Residency is code-keyed and fully associative over the */
/* 49 physical cells left by fixed Plane B + worst-record Plane A.           */
/* ========================================================================= */
    .equ NATIVE_SAT_MAX, 80
    .equ NATIVE_CELLS, 49
    .if (SPRITE_TILE_BASE + NATIVE_CELLS * 4) > 1536
    .error "native sprite VRAM ownership exceeds physical pattern slots"
    .endif
    .equ NATIVE_QUEUE_ENTRY_BYTES, 8
    .equ NATIVE_LANE_HUD, 0
    .equ NATIVE_LANE_FRONT_EFFECT, 1
    .equ NATIVE_LANE_PLAYER_FRONT, 2
    .equ NATIVE_LANE_MIDDLE, 3
    .equ NATIVE_LANE_PLAYER_BODY, 4
    .equ NATIVE_LANE_BACK_ENEMY, 5
    .equ NATIVE_HUD_BOUND, 9
    .equ NATIVE_FRONT_EFFECT_BOUND, 36
    .equ NATIVE_PLAYER_FRONT_BOUND, 30
    .equ NATIVE_MIDDLE_BOUND, 24
    .equ NATIVE_PLAYER_BODY_BOUND, 20
    .equ NATIVE_BACK_ENEMY_BOUND, 99

/* d1=word0, d7=colbank -> d0 = Genesis palette line (Build 0210 semantics). */
.Lnative_palsel:
    movem.l %d1-%d3, -(%sp)
    move.w  %d1, %d0
    andi.w  #0x000F, %d0
    or.w    %d7, %d0
    cmpi.w  #0x0030, %d0
    bne.s   .Lnp_not48
    moveq   #2, %d0
    bra.s   .Lnp_done
.Lnp_not48:
    cmpi.w  #0x0033, %d0
    bne.s   .Lnp_general
    moveq   #3, %d0
    bra.s   .Lnp_done
.Lnp_general:
.if RASTAN_GAMEPLAY_HUD_SPRITES != 1
    move.w  %d0, %d2                 /* d2 = effective bank */
    moveq   #0, %d0
    move.b  genesistan_current_scene_id, %d0
    moveq   #PROUTE_OWNER_PC090OJ_ID, %d1
    bsr     palette_route_lookup     /* d0 = line or -1; clobbers d0/d3/a0 */
    tst.l   %d0
    bpl.s   .Lnp_done
    movem.l (%sp), %d1-%d3           /* reload live regs, no pop */
    move.w  %d1, %d0
    andi.w  #0x000F, %d0
    or.w    %d7, %d0
.endif
    lsr.w   #4, %d0
    andi.w  #0x0003, %d0
.Lnp_done:
	    movem.l (%sp)+, %d1-%d3
	    rts

/* PC090OJ final teardown: .Lpc090oj_mode2_project_p1_hud REMOVED.  It projected the
 * P1 score into object-RAM records 0..8 for a gameplay object-scan path that is no
 * longer reachable (gameplay uses .Lnq_gameplay / .Lnq_project_p1_hud natively). */


/* Build 0250 native semantic-lane finalizer.  Non-gameplay falls back to the
 * legacy object-table scanner; gameplay consumes only the native queues. */
pc090oj_native_emit_pass:
    move.b  genesistan_current_scene_id, %d0
    cmpi.b  #PC090OJ_SCENE_GAMEPLAY_ID, %d0
    beq     .Lnq_gameplay
    tst.b   %d0
    bne     .Lnq_frontend_native        /* scene != 0 and != 1 (scene 2): native frontend */
    /* scene 0 (title tileset): the static native title HUD table is exact only in
     * the title-active state (arcade stage a5@0x118 == 0).  Once the attract loop
     * advances (stage != 0: PUSH-BUTTON text toggles off, sub-screens), the frontend
     * runs the same native producers (HUD + transient items) as scene 2. */
    tst.w   0x00FF0118
    bne     .Lnq_frontend_native
    bra     .Lnq_title
/* Build 0264: title-screen sprites produced by LIVE direct-native producers.
 * Fixed text is a semantic glyph sequence (.Lnq_title_labels: {Y,X,glyph}); the
 * score and high-score digits are generated every frame from the live arcade
 * BCD values (player 0x00FF011E, high score 0x00FF0142) -- no captured digit
 * constants.  Every piece is emitted straight into staged_sprite_sat through
 * the residency + SAT builder the gameplay lanes use: no pc090oj_object_ram,
 * no 0xD00000, no Y=0x180 park, no object-RAM scan.  Scene 0 title-active never
 * reaches .Lnq_frontend_object_scan; other frontend scenes keep the object-RAM
 * path unchanged. */
.Lnq_title:
    movem.l %d0-%d7/%a0-%a3, -(%sp)
    movem.l %a4-%a6, -(%sp)
    lea     staged_sprite_sat, %a3
    tst.w   pc090oj_sat_bank
    beq.s   .Lnq_title_bank_ok
    lea     staged_sprite_sat_b, %a3
.Lnq_title_bank_ok:
    lea     sprite_tile_resident_code, %a2
    lea     pc090oj_cell_used, %a1
    clr.l   (%a1)+
    clr.l   (%a1)+
    clr.l   (%a1)+
    clr.l   (%a1)+
    moveq   #0, %d5
    bsr     native_frontend_hud_emit     /* labels + scores + credit (unified) */
    movem.l (%sp)+, %a4-%a6
    bra     .Lnq_done_scan

/* Fixed-label glyph sequence emitter (semantic {Y,X,glyph}, 0xFFFF-terminated).
 * Each glyph is passed in registers straight to the shared native SAT builder. */
.Lnq_title_emit_labels:
    lea     .Lnq_title_labels, %a5
.Ltl_loop:
    move.w  (%a5), %d2                /* Y */
    cmpi.w  #0xFFFF, %d2
    beq.s   .Ltl_done
    move.w  2(%a5), %d4               /* X */
    move.w  4(%a5), %d3               /* glyph code */
    moveq   #0, %d1                   /* attr = 0 (palette line 0) */
    bsr     .Lnq_emit_entry
    addq.l  #6, %a5
    bra.s   .Ltl_loop
.Ltl_done:
    rts

/* Frontend-direct transient treasure/item emitter.  Replaces the former
 * object-RAM tuple representation for arcade 0x56114/0x5607C/0x56440.  When the
 * family is active, walk the latched ROM tuple stream ({word0/attr, Y, code, X},
 * 0xFFFF-terminated on word0) and emit each piece straight to the native SAT via
 * the shared .Lnq_emit_entry (identical coordinate/flip/viewport transform as the
 * retired object-RAM scanner).  The uniform scroll-up is applied as Y' = Y -
 * scroll, and an item is dropped once Y' <= 16 -- exactly the arcade decay's
 * per-record blank-at-16.  Off-screen (not-yet-scrolled-in) pieces are clipped by
 * .Lnq_emit_entry's viewport test and consume no SAT slot. */
.Lnq_transient_items_emit:
    tst.w   transient_items_active
    beq     .Lti_done
    move.l  transient_items_source_ptr, %a5
    move.l  %a5, %d0                 /* CPU-legality fix: `tst.l %a5` (0x4A8D) is a 68020+
                                       * instruction, illegal on the Genesis 68000 (item-page
                                       * crash @ GEN PC 0x073212).  move.l An,Dn (0x200D) is the
                                       * byte-neutral legal equivalent: same Z=(a5==0) for the
                                       * beq below.  D0 is dead here (proven: sole caller reloads
                                       * d0 after this call, and the loop's .Lnq_emit_entry
                                       * already clobbers d0). */
    beq     .Lti_done
.Lti_loop:
    move.w  (%a5), %d1               /* word0 = attr, or 0xFFFF terminator */
    cmpi.w  #0xFFFF, %d1
    beq.s   .Lti_done
    move.w  2(%a5), %d2              /* Y */
    sub.w   transient_items_scroll, %d2
    cmpi.w  #16, %d2                 /* scrolled past 16 => blanked (retired) */
    ble.s   .Lti_next
    move.w  4(%a5), %d3              /* code */
    move.w  6(%a5), %d4              /* X */
    bsr     .Lnq_emit_entry
.Lti_next:
    addq.l  #8, %a5
    bra.s   .Lti_loop
.Lti_done:
    rts

/* Direct-native replacement of the retired arcade producer 0x5A502 (the
 * no-human attract/demo eight-glyph GAME OVER row -- NOT the human terminal
 * GAME OVER screen, which is a separate 0x03A420 (2,4,5/6) path).  Invoked from
 * the GAMEPLAY native finalizer under the exact original semantic ownership of
 * the 0x05104E caller (Cody_frontend_gameover_highscore_semantic_model.md): the
 * game-flow state tuple must be active no-human attract gameplay, and the
 * gameplay blink phase must be visible.  This corrects the Build0286 defect
 * where the broad .Lnq_frontend_object_scan ownership let the row appear on the
 * HIGH SCORE TABLE (which also has a5+0x34==0 and can observe bit5 clear).
 * a5 = 0xFF0000; the check reads absolute WRAM (a5 is reused below as the label
 * walker, so it is saved/restored).  Records nothing to object RAM; no Y=0x180
 * park (hidden => emit nothing). */
.Lnq_gameover_emit:
    cmpi.w  #2, 0x00FF0000           /* a5+0x00: gameplay/session umbrella */
    bne     .Lgo_ret
    cmpi.w  #3, 0x00FF0002           /* a5+0x02: active/attract-demo gameplay */
    bne     .Lgo_ret
    move.w  0x00FF0004, %d0          /* a5+0x04: nested state 0 or 1 */
    cmpi.w  #1, %d0
    bhi     .Lgo_ret
    tst.w   0x00FF0034               /* a5+0x34: 0 = no-human/attract session */
    bne     .Lgo_ret
    move.w  0x00FF0200, %d0          /* a5+0x200: gameplay frame/phase tick */
    btst    #5, %d0
    bne     .Lgo_ret                 /* bit5 set => hidden phase */
    move.l  %a5, -(%sp)
    lea     .Lnq_gameover_labels, %a5
.Lgo_loop:
    move.w  (%a5), %d4               /* X, or 0xFFFF terminator */
    cmpi.w  #0xFFFF, %d4
    beq.s   .Lgo_pop
    move.w  2(%a5), %d3              /* glyph code */
    move.w  #0x0070, %d2             /* Y = visible */
    moveq   #0, %d1                  /* attr = palette line 0 */
    bsr     .Lnq_emit_entry
    addq.l  #4, %a5
    bra.s   .Lgo_loop
.Lgo_pop:
    move.l  (%sp)+, %a5
.Lgo_ret:
    rts

/* GAME OVER fixed glyph layout: {X, code}.  Codes 0x37,0x38,0x3F,0x40..0x44 =
 * G,A,M,E,O,V,E,R; X 0x60..0x90 then a +0x20 gap then 0xB0..0xE0 -- the exact
 * positions the arcade producer packed into records 83..90. */
.Lnq_gameover_labels:
    .word 0x0060, 0x0037            /* G */
    .word 0x0070, 0x0038            /* A */
    .word 0x0080, 0x003F            /* M */
    .word 0x0090, 0x0040            /* E */
    .word 0x00B0, 0x0041            /* O */
    .word 0x00C0, 0x0042            /* V */
    .word 0x00D0, 0x0043            /* E */
    .word 0x00E0, 0x0044            /* R */
    .word 0xFFFF

/* -------------------------------------------------------------------------
 * native_frontend_hud_emit -- the complete native frontend HUD subsystem.
 *
 * Single semantic owner of the ENTIRE frontend HUD: player + high-score digits,
 * the credit count, AND the fixed HUD text/labels (HIGH SCORE / 1P / 2UP row,
 * etc.).  Invoked at the frontend boundary -- from .Lnq_title for the
 * title-active state and from the top of .Lnq_frontend_object_scan for every
 * other frontend scene.  Every element is generated directly from live
 * semantic state (BCD 0x00FF011E/0x00FF0142, credit 0x00FF0117) or fixed
 * layout (.Lnq_title_labels) straight into the native SAT via .Lnq_emit_entry.
 *
 * Build 0273: this replaces the arcade PC090OJ HUD producer at the arcade-code
 * boundary.  The arcade builder 0x3B8B0 (records 4..45, via the generic 0x3B930
 * copier) is retired to `rts` (opcode_replace), and the arcade credit builder
 * 0x3B902 (records 17..21) is retired to `rts` in its hook -- so no arcade
 * PC090OJ HUD record is produced at all, the object-RAM scanner renders none of
 * this family, and the Build-0272 write-then-clear workaround is deleted.  The
 * generic 0x3B930 copier is preserved untouched.  Because .Lnq_emit_entry
 * applies the IDENTICAL coordinate transform as .Lpc090oj_decode_record, the
 * native labels reproduce the former scan output exactly. */
native_frontend_hud_emit:
    bsr     .Lnq_title_emit_scores       /* live scores + credit -> native SAT */
    bsr     .Lnq_title_emit_labels       /* fixed HUD labels -> native SAT */
    rts

/* Live score/high-score digit producers. */
.Lnq_title_emit_scores:
    lea     0x00FF011E, %a5           /* player score MSB byte */
    move.w  #0x0008, %d0
    movea.w %d0, %a4                  /* leftmost digit X (MSD) */
    moveq   #0, %d0
    movea.w %d0, %a6                  /* Y = 0x0000 */
    bsr     .Lnq_title_emit_digit_group
    lea     0x00FF011E, %a5           /* right-hand score column */
    move.w  #0x00E8, %d0
    movea.w %d0, %a4
    moveq   #0, %d0
    movea.w %d0, %a6
    bsr     .Lnq_title_emit_digit_group
    lea     0x00FF0142, %a5           /* high-score MSB byte */
    move.w  #0x0080, %d0
    movea.w %d0, %a4
    move.w  #0x0010, %d0
    movea.w %d0, %a6                  /* Y = 0x0010 */
    bsr     .Lnq_title_emit_digit_group
    /* Build 0270: native credit-line digits (retires the last 0x3B802 consumer).
     * Shown only when a credit exists (0x00FF0117 > 0), matching the arcade: the
     * credit records are parked off-screen in attract.  Two single digits at
     * their arcade layout (0x00FF0117 -> X 0x128 / Y 0xE8; 0x00FF0103 -> X 0x00 /
     * Y 0xE4), always shown when present (arcade count==1 = no zero suppression).
     * "CREDIT" label glyphs still render from the frontend scan. */
    tst.b   0x00FF0117
    beq.s   .Lnq_no_credits
    moveq   #0, %d1
    move.w  #0x00E8, %d2
    moveq   #0, %d3
    move.b  0x00FF0117, %d3
    andi.w  #0x000F, %d3
    addi.w  #0x002A, %d3
    move.w  #0x0128, %d4
    bsr     .Lnq_emit_entry
.Lnq_no_credits:
    rts

/* a5 = BCD MSB byte (read toward lower addresses), a4 = MSD X, a6 = Y.  Six
 * digits MSD-first, X stepping +8, glyph = 0x2A + nibble, passed in registers
 * to .Lnq_emit_entry (no scratch).  Reproduces the arcade 0x3B802 leading-zero
 * rule: leading zeros are suppressed (not emitted) until the first nonzero
 * digit, so the value is right-justified at fixed positions.  d7 low byte =
 * digit index, bit 8 = seen-nonzero flag. */
.Lnq_title_emit_digit_group:
    moveq   #0, %d7
.Ltdg_loop:
    move.w  %d7, %d0
    andi.w  #0x00FF, %d0              /* index */
    lsr.w   #1, %d0                   /* byte offset from MSB */
    movea.l %a5, %a0
    suba.w  %d0, %a0
    moveq   #0, %d0
    move.b  (%a0), %d0                /* live BCD byte */
    btst    #0, %d7
    bne.s   .Ltdg_low
    lsr.w   #4, %d0                   /* high nibble on even index */
.Ltdg_low:
    andi.w  #0x000F, %d0             /* digit value */
    btst    #8, %d7                  /* already seen a nonzero digit? */
    bne.s   .Ltdg_show
    tst.w   %d0
    beq.s   .Ltdg_suppress           /* leading zero -> suppress (emit nothing) */
.Ltdg_show:
    bset    #8, %d7
    addi.w  #0x002A, %d0             /* digit -> glyph code */
    move.w  %d0, %d3
    move.l  %a6, %d2                 /* Y */
    move.l  %a4, %d4                 /* X */
    moveq   #0, %d1                  /* attr */
    move.w  %d7, -(%sp)
    bsr     .Lnq_emit_entry
    move.w  (%sp)+, %d7
.Ltdg_suppress:
    addq.l  #8, %a4                  /* fixed position advances even when suppressed */
    addq.w  #1, %d7
    move.w  %d7, %d0
    andi.w  #0x00FF, %d0
    cmpi.w  #6, %d0
    blo.s   .Ltdg_loop
    rts

/* Build 0273: the Build-0272 write-then-clear workaround (.Lnq_hud_clear_records
 * + .Lnq_hud_owned_records) is DELETED.  The arcade HUD PC090OJ builders (0x3B8B0
 * and the 0x3B902 hook) are retired at the arcade-code boundary, so no HUD record
 * is produced and nothing needs clearing. */

    .align 2
/* Fixed frontend HUD text as a semantic glyph sequence: {Y, X, glyph_code},
 * letters and symbols only (codes >= 0x34); all numeric digits are produced live
 * above.  These values are the exact object-RAM label records the arcade builder
 * formerly wrote; .Lnq_emit_entry applies the same transform as the retired scan
 * path, so native output reproduces the former labels byte-for-byte.
 * 0xFFFF Y terminates. */
.Lnq_title_labels:
    .word 0x0000,0x0078,0x003A
    .word 0x0000,0x0088,0x003B
    .word 0x0000,0x0098,0x003C
    .word 0x0000,0x00A8,0x003D
    .word 0x0008,0x00B8,0x003E
    .word 0x00F8,0x0008,0x0037
    .word 0x00F8,0x0018,0x0038
    .word 0x00F8,0x0030,0x0045
    .word 0x00F8,0x0040,0x0045
    .word 0x00F8,0x0050,0x0045
    .word 0x00F8,0x0060,0x0045
    .word 0x00F8,0x0070,0x0045
    .word 0x00F8,0x0080,0x0045
    .word 0x01E8,0x0100,0x0034
    .word 0x01E8,0x0110,0x0035
    .word 0x01E8,0x0120,0x0036
    .word 0x0010,0x0040,0x0039
    .word 0x0000,0x0028,0x0048
    .word 0x0000,0x0038,0x0046
    .word 0x0010,0x0120,0x0039
    .word 0x0000,0x0108,0x0049
    .word 0x0000,0x0118,0x0047
    .word 0xFFFF,0x0000,0x0000
.Lnq_gameplay:
    movem.l %d0-%d7/%a0-%a3, -(%sp)
    lea     staged_sprite_sat, %a3
    tst.w   pc090oj_sat_bank
    beq.s   .Lnq_bank_ok
    lea     staged_sprite_sat_b, %a3
.Lnq_bank_ok:
.if RASTAN_GAMEPLAY_HUD_SPRITES == 2
    bsr     .Lnq_project_p1_hud
.endif
    lea     sprite_tile_resident_code, %a2
    lea     pc090oj_cell_used, %a1
    clr.l   (%a1)+
    clr.l   (%a1)+
    clr.l   (%a1)+
    clr.l   (%a1)+
    moveq   #0, %d5

    lea     native_queue_hud, %a0
    move.w  native_hud_count, %d6
    bsr     .Lnq_emit_lane
    lea     native_queue_front_effect, %a0
    move.w  native_front_effect_count, %d6
    bsr     .Lnq_emit_lane
    lea     native_queue_player_front, %a0
    move.w  native_player_front_count, %d6
    bsr     .Lnq_emit_lane
    lea     native_queue_middle, %a0
    move.w  native_middle_count, %d6
    bsr     .Lnq_emit_lane
    lea     native_queue_player_body, %a0
    move.w  native_player_body_count, %d6
    bsr     .Lnq_emit_lane
    lea     native_queue_back_enemy, %a0
    move.w  native_back_enemy_count, %d6
    bsr     .Lnq_emit_lane
    /* Direct-native 0x5A502 attract/demo GAME OVER row -- owned here in the
     * gameplay finalizer under its exact original 0x05104E state gate, appended
     * after the native lanes (shares this pass's a3/a2/a1/d5 SAT context). */
    bsr     .Lnq_gameover_emit
    bra     .Lnq_done_scan

.if RASTAN_GAMEPLAY_HUD_SPRITES == 2
.Lnq_project_p1_hud:
    movem.l %d0-%d7/%a0-%a2, -(%sp)
    clr.w   native_hud_count
    move.w  #NATIVE_LANE_HUD, native_sprite_lane
    movea.l #0x00FF011E, %a2
    clr.w   %d5

    moveq   #0, %d1
    move.b  (%a2), %d1
    lsr.b   #4, %d1
    andi.w  #0x000F, %d1
    moveq   #0x08, %d4
    bsr     .Lnq_emit_hud_digit

    moveq   #0, %d1
    move.b  (%a2), %d1
    andi.w  #0x000F, %d1
    moveq   #0x10, %d4
    bsr     .Lnq_emit_hud_digit
    subq.l  #1, %a2

    moveq   #0, %d1
    move.b  (%a2), %d1
    lsr.b   #4, %d1
    andi.w  #0x000F, %d1
    moveq   #0x18, %d4
    bsr     .Lnq_emit_hud_digit

    moveq   #0, %d1
    move.b  (%a2), %d1
    andi.w  #0x000F, %d1
    moveq   #0x20, %d4
    bsr     .Lnq_emit_hud_digit
    subq.l  #1, %a2

    moveq   #0, %d1
    move.b  (%a2), %d1
    lsr.b   #4, %d1
    andi.w  #0x000F, %d1
    moveq   #0x28, %d4
    bsr     .Lnq_emit_hud_digit

    moveq   #0, %d1
    move.b  (%a2), %d1
    andi.w  #0x000F, %d1
    moveq   #0x30, %d4
    bsr     .Lnq_emit_hud_digit

    moveq   #0, %d1
    move.w  #0x0010, %d2
    move.w  #0x8039, %d3
    move.w  #0x0040, %d4
    bsr     native_sprite_emit
    moveq   #0, %d1
    move.w  #0x0010, %d2
    move.w  #0x8048, %d3
    move.w  #0x0028, %d4
    bsr     native_sprite_emit
    moveq   #0, %d1
    move.w  #0x0010, %d2
    move.w  #0x8046, %d3
    move.w  #0x0038, %d4
    bsr     native_sprite_emit
    movem.l (%sp)+, %d0-%d7/%a0-%a2
    rts
.Lnq_emit_hud_digit:
    move.w  #0x0010, %d2
    tst.w   %d5
    bne.s   .Lnq_digit_visible
    tst.w   %d1
    bne.s   .Lnq_digit_visible
    move.w  #0x0110, %d2
    bra.s   .Lnq_digit_ready
.Lnq_digit_visible:
    moveq   #1, %d5
.Lnq_digit_ready:
    addi.w  #0x002A, %d1
    ori.w   #0x8000, %d1
    move.w  %d1, %d3
    moveq   #0, %d1
    bsr     native_sprite_emit
    rts
.endif

.Lnq_emit_lane:
    tst.w   %d6
    beq     .Lnq_lane_done
    subq.w  #1, %d6
.Lnq_lane_loop:
    move.w  (%a0)+, %d1
    move.w  (%a0)+, %d2
    move.w  (%a0)+, %d3
    move.w  (%a0)+, %d4
    move.w  %d6, -(%sp)
    bsr     .Lnq_emit_entry
    move.w  (%sp)+, %d6
    cmpi.w  #NATIVE_SAT_MAX, %d5
    bhs.s   .Lnq_lane_done
    dbra    %d6, .Lnq_lane_loop
.Lnq_lane_done:
    rts

.Lnq_emit_entry:
    move.w  %d3, %d0
    andi.w  #0x1FFF, %d0
    beq     .Lnq_entry_skip
    cmpi.w  #0x1000, %d0
    bhs     .Lnq_entry_skip
    move.w  %d0, %d6
    lsr.w   #3, %d6
    lea     pc090oj_blank_code_bitset, %a1
    move.b  0(%a1,%d6.w), %d6
    move.w  %d0, %d7
    andi.w  #0x0007, %d7
    btst    %d7, %d6
    bne     .Lnq_entry_skip
    /* Preserve HUD-white residency tag from the caller's code bit 15.  Taken from
     * d3 directly (not a memory operand), so .Lnq_emit_entry is callable both by
     * the lane loader and directly with d1=attr/d2=Y/d3=code/d4=X in registers. */
    btst    #15, %d3
    sne     %d6
    move.w  %d0, %d3
    tst.b   %d6
    beq.s   .Lnq_no_hud_tag
    ori.w   #0x8000, %d3
.Lnq_no_hud_tag:

    andi.w  #0x01FF, %d2
    cmpi.w  #0x0140, %d2
    bls.s   .Lnq_y_ok
    subi.w  #0x0200, %d2
.Lnq_y_ok:
    andi.w  #0x01FF, %d4
    cmpi.w  #0x0140, %d4
    bls.s   .Lnq_x_ok
    subi.w  #0x0200, %d4
.Lnq_x_ok:
    move.w  pc090oj_ctrl_shadow, %d6
    btst    #0, %d6
    bne.s   .Lnq_no_flip
    move.w  #PC090OJ_FLIP_X_TERM, %d6
    sub.w   %d4, %d6
    move.w  %d6, %d4
    move.w  #PC090OJ_FLIP_Y_TERM, %d6
    sub.w   %d2, %d6
    move.w  %d6, %d2
    eori.w  #0xC000, %d1
.Lnq_no_flip:
    addi.w  #PC090OJ_TO_GENESIS_X_OFFSET, %d4
    addi.w  #PC090OJ_TO_GENESIS_Y_OFFSET, %d2

    move.w  %d3, %d0
    andi.w  #0x0FFF, %d0
    lsl.w   #2, %d0
    lea     pc090oj_opaque_bbox, %a1
    adda.w  %d0, %a1
    moveq   #0, %d0
    move.b  0(%a1), %d0
    moveq   #0, %d6
    move.b  1(%a1), %d6
    btst    #15, %d1
    beq.s   .Lnq_vrows_ok
    neg.w   %d0
    addi.w  #PC090OJ_PATTERN_MAX_ROW, %d0
    neg.w   %d6
    addi.w  #PC090OJ_PATTERN_MAX_ROW, %d6
    exg     %d0, %d6
.Lnq_vrows_ok:
    add.w   %d2, %d0
    add.w   %d2, %d6
    cmpi.w  #GENESIS_VIEWPORT_BOTTOM, %d0
    bge     .Lnq_entry_skip
    cmpi.w  #GENESIS_VIEWPORT_TOP, %d6
    blt     .Lnq_entry_skip
    moveq   #0, %d0
    move.b  2(%a1), %d0
    moveq   #0, %d6
    move.b  3(%a1), %d6
    btst    #14, %d1
    beq.s   .Lnq_hcols_ok
    neg.w   %d0
    addi.w  #PC090OJ_PATTERN_MAX_COL, %d0
    neg.w   %d6
    addi.w  #PC090OJ_PATTERN_MAX_COL, %d6
    exg     %d0, %d6
.Lnq_hcols_ok:
    add.w   %d4, %d0
    add.w   %d4, %d6
    cmpi.w  #GENESIS_VIEWPORT_RIGHT, %d0
    bge     .Lnq_entry_skip
    cmpi.w  #GENESIS_VIEWPORT_LEFT, %d6
    blt     .Lnq_entry_skip

    /* Full bounded lookup avoids artificial set conflicts in the 49-cell physical band. */
    moveq   #0, %d0
    move.w  #(NATIVE_CELLS - 1), %d6
.Lnq_lookup_loop:
    cmp.w   0(%a2,%d0.w), %d3
    beq     .Lnq_hit
    addq.w  #2, %d0
    dbra    %d6, .Lnq_lookup_loop
    move.w  %d1, -(%sp)
    moveq   #0, %d0
    move.w  #(NATIVE_CELLS - 1), %d1
.Lnq_vloop:
    bsr     .Lnq_cell_free
    beq.s   .Lnq_take
    addq.w  #2, %d0
    dbra    %d1, .Lnq_vloop
    move.w  (%sp)+, %d1
    addq.w  #1, pc090oj_dropped_count
    bra     .Lnq_entry_skip
.Lnq_take:
    move.w  pc090oj_tile_dma_count, %d1
    cmpi.w  #12, %d1
    bhs.s   .Lnq_qfull
    lea     pc090oj_tile_dma_worklist, %a1
    lsl.w   #2, %d1
    adda.w  %d1, %a1
    move.w  %d0, %d1
    lsr.w   #1, %d1
    move.w  %d1, (%a1)+
    move.w  %d3, (%a1)
    addq.w  #1, pc090oj_tile_dma_count
    move.w  %d3, 0(%a2,%d0.w)
    move.w  (%sp)+, %d1
    bra     .Lnq_hit
.Lnq_qfull:
    move.w  (%sp)+, %d1
    addq.w  #1, pc090oj_dropped_count
    bra     .Lnq_entry_skip
.Lnq_cell_free:
    move.w  %d0, -(%sp)
    lea     pc090oj_cell_used, %a1
    lsr.w   #4, %d0
    adda.w  %d0, %a1
    move.w  (%sp), %d0
    lsr.w   #1, %d0
    andi.w  #7, %d0
    btst    %d0, (%a1)
    movem.w (%sp)+, %d0
    rts
.Lnq_hit:
    move.w  %d0, -(%sp)
    lea     pc090oj_cell_used, %a1
    lsr.w   #4, %d0
    adda.w  %d0, %a1
    move.w  (%sp), %d0
    lsr.w   #1, %d0
    andi.w  #7, %d0
    bset    %d0, (%a1)
    move.w  (%sp)+, %d0
    move.w  %d0, -(%sp)
    move.w  %d2, %d0
    andi.w  #0x01FF, %d0
    addi.w  #PC090OJ_SAT_Y_BIAS, %d0
    andi.w  #0x01FF, %d0
    move.w  %d0, (%a3)+
    move.w  %d5, %d0
    addq.w  #1, %d0
    andi.w  #0x007F, %d0
    ori.w   #0x0500, %d0
    move.w  %d0, (%a3)+
    move.w  %d1, %d0
    andi.w  #0x000F, %d0
    lea     pc090oj_sat_nibble, %a1
    move.b  %d0, 0(%a1,%d5.w)
.if RASTAN_GAMEPLAY_HUD_SPRITES == 2
    lea     pc090oj_sat_force_line, %a1
    move.b  #0xFF, 0(%a1,%d5.w)
    btst    #15, %d3
    beq.s   .Lnq_no_force_line
    move.b  #3, 0(%a1,%d5.w)
.Lnq_no_force_line:
.endif
    moveq   #0, %d0
    ori.w   #0x8000, %d0
    btst    #15, %d1
    beq.s   .Lnq_novf
    ori.w   #0x1000, %d0
.Lnq_novf:
    btst    #14, %d1
    beq.s   .Lnq_nohf
    ori.w   #0x0800, %d0
.Lnq_nohf:
    move.w  (%sp)+, %d2
    add.w   %d2, %d2
    addi.w  #SPRITE_TILE_BASE, %d2
    andi.w  #0x07FF, %d2
    or.w    %d2, %d0
    move.w  %d0, (%a3)+
    move.w  %d4, %d0
    andi.w  #0x01FF, %d0
    addi.w  #PC090OJ_SAT_X_BIAS, %d0
    andi.w  #0x01FF, %d0
    move.w  %d0, (%a3)+
    addq.w  #1, %d5
.Lnq_entry_skip:
    rts

.Lnq_done_scan:
    tst.w   %d5
    bne.s   .Lnq_have
    clr.w   (%a3)+
    clr.w   (%a3)+
    clr.w   (%a3)+
    clr.w   (%a3)+
    bra.s   .Lnq_store
.Lnq_have:
    move.w  -6(%a3), %d0
    andi.w  #0xFF80, %d0
    move.w  %d0, -6(%a3)
.Lnq_store:
    move.w  %d5, pc090oj_emitted_count
    move.w  #1, pc090oj_sat_frame_ready
    move.w  #1, pc090oj_sat_dirty
    movem.l (%sp)+, %d0-%d7/%a0-%a3
    rts

/* Frontend / non-gameplay native finalizer (PC090OJ final teardown).  The former
 * .Lnq_frontend_object_scan + its 256-record object-RAM loop, decoder, and
 * residency tail are REMOVED; every frontend sprite is produced by native
 * Genesis owners.  This mirrors .Lnq_title's setup plus the transient item/effect
 * family, then hands off to the shared native finalizer .Lnq_done_scan.  Reached
 * for scene 0 stage!=0 and scene 2 from pc090oj_native_emit_pass. */
.Lnq_frontend_native:
    movem.l %d0-%d7/%a0-%a3, -(%sp)
    movem.l %a4-%a6, -(%sp)
    lea     staged_sprite_sat, %a3
    tst.w   pc090oj_sat_bank
    beq.s   .Lnqfn_bank_ok
    lea     staged_sprite_sat_b, %a3
.Lnqfn_bank_ok:
    lea     sprite_tile_resident_code, %a2
    lea     pc090oj_cell_used, %a1     /* per-frame referenced-cell bitmap */
    clr.l   (%a1)+
    clr.l   (%a1)+
    clr.l   (%a1)+
    clr.l   (%a1)+
    moveq   #0, %d5                    /* d5 = emitted count / cursor */
    bsr     native_frontend_hud_emit     /* live scores/labels/credit */
    bsr     .Lnq_transient_items_emit    /* frontend-direct treasure/item family */
    movem.l (%sp)+, %a4-%a6
    bra     .Lnq_done_scan

/* Commit-time palette resolution: apply the DISPLAY-LATCHED colbank to every
 * emitted entry (<=80 iterations).  d7 = colbank from the current sprite_ctrl
 * shadow; per entry d1 = stored bank nibble -> .Lnative_palsel line. */
.Lnative_pal_fixup:
    movem.l %d0-%d7/%a0-%a3, -(%sp)
    move.w  pc090oj_emitted_count, %d6
    beq.s   .Lnpf_done
    lea     staged_sprite_sat, %a3
    tst.w   pc090oj_sat_front
    beq.s   .Lnpf_base_ok
    lea     staged_sprite_sat_b, %a3
	.Lnpf_base_ok:
	    lea     pc090oj_sat_nibble, %a2
	.if RASTAN_GAMEPLAY_HUD_SPRITES == 2
	    lea     pc090oj_sat_force_line, %a1
	.endif
	    move.w  pc090oj_sprite_ctrl_shadow, %d7
	    andi.w  #0x00E0, %d7
	    lsr.w   #1, %d7
	    moveq   #0, %d5
	.Lnpf_loop:
	    moveq   #0, %d1
	    move.b  0(%a2,%d5.w), %d1
	.if RASTAN_GAMEPLAY_HUD_SPRITES == 2
	    moveq   #0, %d0
	    move.b  0(%a1,%d5.w), %d0
	    cmpi.b  #0xFF, %d0
	    bne.s   .Lnpf_line_ready
	.endif
	    bsr     .Lnative_palsel            /* d1 nibble + d7 colbank -> d0 line */
	.Lnpf_line_ready:
	    lsl.w   #8, %d0
	    lsl.w   #5, %d0
    move.w  4(%a3), %d1
    andi.w  #0x9FFF, %d1               /* clear palette bits */
    or.w    %d0, %d1
    move.w  %d1, 4(%a3)
    adda.w  #8, %a3
    addq.w  #1, %d5
    cmp.w   %d6, %d5
    blo.s   .Lnpf_loop
.Lnpf_done:
    movem.l (%sp)+, %d0-%d7/%a0-%a3
    rts

/* VBlank entry (called by _vblank_service): frontend fallback pass only.    */
vdp_prepare_sprites:
    tst.w   pc090oj_sat_frame_ready
    bne.s   .Lvps_done
    bsr     pc090oj_native_emit_pass
.Lvps_done:
    rts

/* VBlank commit: pattern uploads, then publish+DMA the finished bank.       */
vdp_commit_sprites:
vdp_commit_sprites_vram:
    movem.l %d0-%d7/%a0-%a6, -(%sp)
    bsr     .Lvcs_tile_dma
    tst.w   pc090oj_sat_frame_ready
    beq.s   .Lvcs_commit_done
    move.w  pc090oj_sat_bank, pc090oj_sat_front
    eori.w  #1, pc090oj_sat_bank
    clr.w   pc090oj_sat_frame_ready
    bsr     .Lnative_pal_fixup
    bsr     .Lvcs_sat_dma
    clr.w   pc090oj_sat_dirty
.Lvcs_commit_done:
    movem.l (%sp)+, %d0-%d7/%a0-%a6
    rts

/* PC090OJ final teardown: .Lpc090oj_decode_record (virtual-record word decode,
 * clip, flip, code, colbank) REMOVED with pc090oj_object_ram and the frontend scan. */

/*
 * Precomputed tile-DMA worklist commit.  Bounded by pc090oj_tile_dma_count,
 * skips canceled entries (code 0xFFFF), updates slot residency only after the
 * DMA, and resets the reservation map + count at the end of the interval.
 */
.Lvcs_tile_dma:
    move.w  pc090oj_tile_dma_count, %d7
    beq     .Lvcs_tile_reset
    moveq   #0, %d5
.Lvcs_tile_loop:
    move.w  %d5, %d0
    lsl.w   #2, %d0
    lea     pc090oj_tile_dma_worklist, %a0
    adda.w  %d0, %a0
    move.w  (%a0), %d4                  /* slot */
    move.w  2(%a0), %d6                /* code (0xFFFF = canceled) */
    cmpi.w  #0xFFFF, %d6
    beq     .Lvcs_tile_next

	    move.w  %d6, %d0
	    andi.w  #0x0FFF, %d0
	.if RASTAN_GAMEPLAY_HUD_SPRITES == 2
	    btst    #15, %d6
	    beq.s   .Lvcs_tile_src_normal
	    move.w  %d0, %d3
	    subi.w  #0x002A, %d3
	    mulu.w  #128, %d3
	    lea     rastan_pc090oj_hud_white, %a1
	    adda.l  %d3, %a1
	    bra.s   .Lvcs_tile_src_ready
	.Lvcs_tile_src_normal:
	.endif
	    mulu.w  #128, %d0
	    lea     rastan_pc090oj, %a1
	    adda.l  %d0, %a1
	.Lvcs_tile_src_ready:
	    move.l  %a1, %d0
    lsr.l   #1, %d0
    movea.l #VDP_CTRL, %a3
    move.w  #0x9340, (%a3)
    move.w  #0x9400, (%a3)
    move.w  %d0, %d3
    andi.w  #0x00FF, %d3
    ori.w   #0x9500, %d3
    move.w  %d3, (%a3)
    move.l  %d0, %d3
    lsr.l   #8, %d3
    andi.w  #0x00FF, %d3
    ori.w   #0x9600, %d3
    move.w  %d3, (%a3)
    move.l  %d0, %d3
    lsr.l   #8, %d3
    lsr.l   #8, %d3
    andi.w  #0x007F, %d3
    ori.w   #0x9700, %d3
    move.w  %d3, (%a3)
    move.w  %d4, %d0
    lsl.w   #2, %d0
    addi.w  #SPRITE_TILE_BASE, %d0
    lsl.l   #5, %d0
    move.l  %d0, %d1
    andi.l  #0x00003FFF, %d1
    swap    %d1
    move.l  %d0, %d2
    lsr.l   #8, %d2
    lsr.l   #6, %d2
    andi.l  #0x00000003, %d2
    ori.l   #0x40000080, %d1
    or.l    %d2, %d1
    move.l  %d1, (%a3)
    move.w  %d4, %d0
    add.w   %d0, %d0
    lea     sprite_tile_resident_code, %a1
    move.w  %d6, 0(%a1,%d0.w)
.Lvcs_tile_next:
    addq.w  #1, %d5
    cmp.w   %d7, %d5
    blo     .Lvcs_tile_loop
.Lvcs_tile_reset:
    /* Reset only the slots actually reserved this interval (d7 = count, still
     * live), so a stable no-work frame (count 0) does zero reset work. */
    tst.w   %d7
    beq.s   .Lvcs_tile_reset_done
    moveq   #0, %d5
.Lvcs_tile_reset_loop:
    move.w  %d5, %d0
    lsl.w   #2, %d0
    lea     pc090oj_tile_dma_worklist, %a0
    adda.w  %d0, %a0
    moveq   #0, %d0
    move.w  (%a0), %d0                  /* reserved slot for this entry */
    lea     worklist_entry_for_slot, %a1
    move.b  #0xFF, 0(%a1,%d0.w)
    addq.w  #1, %d5
    cmp.w   %d7, %d5
    blo.s   .Lvcs_tile_reset_loop
.Lvcs_tile_reset_done:
    clr.w   pc090oj_tile_dma_count
    rts

/* SAT DMA: length = max(highest_used+1, 1) * 4 words, clamped to 80 slots. */
.Lvcs_sat_dma:
    movea.l #VDP_CTRL, %a3
    move.w  #80, %d0                   /* constant full-table DMA (640 B) */
    lsl.w   #2, %d0

    move.w  %d0, %d1
    andi.w  #0x00FF, %d1
    ori.w   #0x9300, %d1
    move.w  %d1, (%a3)

    move.w  %d0, %d1
    lsr.w   #8, %d1
    andi.w  #0x00FF, %d1
    ori.w   #0x9400, %d1
    move.w  %d1, (%a3)

    move.l  #staged_sprite_sat, %d0
    tst.w   pc090oj_sat_front
    beq.s   .Lsat_src_ok
    move.l  #staged_sprite_sat_b, %d0
.Lsat_src_ok:
    lsr.l   #1, %d0

    move.w  %d0, %d1
    andi.w  #0x00FF, %d1
    ori.w   #0x9500, %d1
    move.w  %d1, (%a3)

    move.l  %d0, %d1
    lsr.l   #8, %d1
    andi.w  #0x00FF, %d1
    ori.w   #0x9600, %d1
    move.w  %d1, (%a3)

    move.l  %d0, %d1
    lsr.l   #8, %d1
    lsr.l   #8, %d1
    andi.w  #0x007F, %d1
    ori.w   #0x9700, %d1
    move.w  %d1, (%a3)

    move.l  #0x0000F800, %d0
    move.l  %d0, %d1
    andi.l  #0x00003FFF, %d1
    swap    %d1
    move.l  %d0, %d2
    lsr.l   #8, %d2
    lsr.l   #6, %d2
    andi.l  #0x00000003, %d2
    ori.l   #0x40000080, %d1
    or.l    %d2, %d1
    move.l  %d1, (%a3)
    rts

/* ------------------------------------------------------------------------- */
/* VRAM DMA self-test                                                        */
/* ------------------------------------------------------------------------- */

genesistan_pc090oj_dma_self_test:
    movem.l %d0-%d7/%a0-%a6, -(%sp)

    /* Stack buffer (128 bytes) */
    lea     -128(%sp), %sp
    movea.l %sp, %a6

    /* DMA source: rastan_pc090oj + 0x80, len 64 words, dest VRAM 0x8000 */
    lea     rastan_pc090oj+0x80, %a1
    move.l  %a1, %d0
    lsr.l   #1, %d0

    movea.l #VDP_CTRL, %a3
    move.w  #0x9340, (%a3)
    move.w  #0x9400, (%a3)

    move.w  %d0, %d1
    andi.w  #0x00FF, %d1
    ori.w   #0x9500, %d1
    move.w  %d1, (%a3)

    move.l  %d0, %d1
    lsr.l   #8, %d1
    andi.w  #0x00FF, %d1
    ori.w   #0x9600, %d1
    move.w  %d1, (%a3)

    move.l  %d0, %d1
    lsr.l   #8, %d1
    lsr.l   #8, %d1
    andi.w  #0x007F, %d1
    ori.w   #0x9700, %d1
    move.w  %d1, (%a3)

    move.l  #0x00008000, %d0
    move.l  %d0, %d1
    andi.l  #0x00003FFF, %d1
    swap    %d1
    move.l  %d0, %d2
    lsr.l   #8, %d2
    lsr.l   #6, %d2
    andi.l  #0x00000003, %d2
    ori.l   #0x40000080, %d1
    or.l    %d2, %d1
    move.l  %d1, (%a3)

    /* Read back VRAM 0x8000..0x807F into stack buffer */
    move.l  #0x00008000, %d0
    move.l  %d0, %d1
    andi.l  #0x00003FFF, %d1
    swap    %d1
    move.l  %d0, %d2
    lsr.l   #8, %d2
    lsr.l   #6, %d2
    andi.l  #0x00000003, %d2
    or.l    %d2, %d1                 /* VRAM read command (no write/dma bits) */
    move.l  %d1, (%a3)

    movea.l #VDP_DATA, %a4
    move.w  #(64 - 1), %d0
.Lpc090oj_dma_read_loop:
    move.w  (%a4), (%a6)+
    dbra    %d0, .Lpc090oj_dma_read_loop

    /* Compare 64 words */
    lea     rastan_pc090oj+0x80, %a0
    movea.l %sp, %a1
    moveq   #0, %d6
    move.w  #(64 - 1), %d0
.Lpc090oj_dma_cmp_loop:
    move.w  (%a0)+, %d1
    move.w  (%a1)+, %d2
    cmp.w   %d1, %d2
    bne.s   .Lpc090oj_dma_fail
    addq.w  #1, %d6
    dbra    %d0, .Lpc090oj_dma_cmp_loop

    lea     128(%sp), %sp
    movem.l (%sp)+, %d0-%d7/%a0-%a6
    rts

.Lpc090oj_dma_fail:
    move.w  %d6, pc090oj_dma_test_mismatch_offset
    move.w  %d1, pc090oj_dma_test_expected_word
    move.w  %d2, pc090oj_dma_test_actual_word

    /* copy full 128-byte snapshot */
    movea.l %sp, %a0
    lea     pc090oj_dma_test_actual_buffer, %a1
    move.w  #(128/2 - 1), %d0
.Lpc090oj_dma_copy_buf:
    move.w  (%a0)+, (%a1)+
    dbra    %d0, .Lpc090oj_dma_copy_buf

    move.w  #0x6F0E, pc090oj_dma_test_fired_flag

.Lpc090oj_dma_test_halt:
    move.b  pc090oj_dma_test_heartbeat, %d0
    addq.b  #1, %d0
    move.b  %d0, pc090oj_dma_test_heartbeat
    bra     .Lpc090oj_dma_test_halt

/* ------------------------------------------------------------------------- */
/* BSS                                                                        */
/* ------------------------------------------------------------------------- */

    .section .bss
    .align 2

/* N1 shadow SAT double buffer (final Genesis SAT format, link-ordered). */
staged_sprite_sat:
    .space (80 * 8)
staged_sprite_sat_b:
    .space (80 * 8)
pc090oj_sat_bank:
    .word 0
pc090oj_sat_front:
    .word 0
pc090oj_sat_frame_ready:
    .word 0
pc090oj_sat_nibble:
	    .space 80
pc090oj_sat_force_line:
	    .space 80
	    .align 2
/* Per-frame referenced-cell bitmap (49 live bits; rounded storage). */
pc090oj_cell_used:
    .space 16
/* Code-keyed residency tags: 49 fully-associative cells (tiles 1339..1534). */
sprite_tile_resident_code:
    .space (NATIVE_CELLS * 2)
/* Bounded VBlank pattern-upload queue: 12 x {word cell, word code}. */
pc090oj_tile_dma_worklist:
    .space (12 * 4)
pc090oj_tile_dma_count:
    .word 0
/* Frontend-direct treasure/item transient family (arcade 0x56114 copy /
 * 0x5607C decay / 0x56440 clear).  Small Genesis-only semantic state that
 * replaces the former object-RAM tuple representation: active flag, the live
 * runtime pointer to the selected ROM tuple stream (0x56226 / 0x562B0, set by
 * the arcade caller's a0), and the accumulated uniform Y decrement (scroll)
 * that the decay produces.  Walked directly by .Lnq_transient_items_emit. */
transient_items_active:
    .word 0
transient_items_scroll:
    .word 0
transient_items_source_ptr:
    .long 0
native_sprite_lane:
    .word 0
native_hud_count:
    .word 0
native_front_effect_count:
    .word 0
native_player_front_count:
    .word 0
native_middle_count:
    .word 0
native_player_body_count:
    .word 0
native_back_enemy_count:
    .word 0
native_queue_hud:
    .space (NATIVE_HUD_BOUND * NATIVE_QUEUE_ENTRY_BYTES)
native_queue_front_effect:
    .space (NATIVE_FRONT_EFFECT_BOUND * NATIVE_QUEUE_ENTRY_BYTES)
native_queue_player_front:
    .space (NATIVE_PLAYER_FRONT_BOUND * NATIVE_QUEUE_ENTRY_BYTES)
native_queue_middle:
    .space (NATIVE_MIDDLE_BOUND * NATIVE_QUEUE_ENTRY_BYTES)
native_queue_player_body:
    .space (NATIVE_PLAYER_BODY_BOUND * NATIVE_QUEUE_ENTRY_BYTES)
native_queue_back_enemy:
    .space (NATIVE_BACK_ENEMY_BOUND * NATIVE_QUEUE_ENTRY_BYTES)
    .align 2
/* Native sprite-control shadows: pc090oj_ctrl_shadow is the global-flip control
 * read by the gameplay flip path; pc090oj_sprite_ctrl_shadow is the colbank
 * latch read by .Lnative_pal_fixup.  Both are live native state (historical name
 * only), NOT PC090OJ compatibility. */
pc090oj_ctrl_shadow:
    .word 0
pc090oj_sprite_ctrl_shadow:
    .word 0
/* Native SAT finalizer state (shared by title/gameplay/frontend). */
pc090oj_emitted_count:
    .word 0
pc090oj_dropped_count:
    .word 0
pc090oj_sat_dirty:
    .word 0
/* Audit-guard + DMA self-test diagnostics (retained consumers). */
audit_guard_caller_pc:
    .long 0
audit_guard_register_snapshot:
    .space (16 * 4)
audit_guard_vcount:
    .word 0
audit_guard_fired_flag:
    .word 0
audit_guard_heartbeat:
    .word 0
    .align 2

/* Native tile-DMA scratch (historical name; live consumer at the tile-DMA
 * commit path). */
worklist_entry_for_slot:
    .space NATIVE_CELLS
    .align 2

    .section .bss.patcher
    .balign 2
pc090oj_dma_test_fired_flag:
    .word 0
pc090oj_dma_test_mismatch_offset:
    .word 0
pc090oj_dma_test_expected_word:
    .word 0
pc090oj_dma_test_actual_word:
    .word 0
pc090oj_dma_test_actual_buffer:
    .space 128
pc090oj_dma_test_heartbeat:
    .byte 0
