    .section .text,"ax"

/* Build 0181: PC090OJ helper mirror sizing is build-time configurable.  The
 * include is generated by apps/rastan-direct/Makefile from PC090OJ_MIRROR_RECORDS
 * (default 256; override e.g. `make release PC090OJ_MIRROR_RECORDS=128`).  It
 * defines PC090OJ_MIRROR_RECORDS, PC090OJ_MIRROR_BYTES (=RECORDS*8) and
 * PC090OJ_BITSET_BYTES (=ceil(RECORDS/8)).  All mirror array sizes, record loop
 * bounds, and the not-found record sentinel derive from these so no scattered
 * assembly constant needs hand-editing. */
    .include "pc090oj_config.inc"

    .global genesistan_pc090oj_hook_target_3b902
    .global genesistan_pc090oj_hook_target_3b926
    .global genesistan_pc090oj_hook_target_3b930
    .global genesistan_pc090oj_hook_target_41dae
    .global genesistan_pc090oj_hook_target_41f5e
    .global genesistan_pc090oj_hook_target_45dfa
    .global genesistan_pc090oj_hook_target_59f5e
    .global genesistan_hook_3ad44_dispatch
    .global genesistan_pc090oj_hook_init_priority_3ad84
    .global genesistan_pc090oj_hook_score_digit_3b802
    .global genesistan_pc090oj_hook_slot_init_54052
    .global genesistan_pc090oj_hook_sprite_update_54810
    .global genesistan_pc090oj_hook_sprite_decay_5607c
    .global genesistan_pc090oj_hook_copy_56114
    .global genesistan_pc090oj_hook_zero_fill_56440
    .global genesistan_pc090oj_hook_status_sprite_5a098
    .global genesistan_pc090oj_hook_audit_guard
    .global genesistan_pc090oj_ctrl_set_1
    .global genesistan_pc090oj_ctrl_set_0
    .global genesistan_pc090oj_sprite_ctrl_write_d0
    .global genesistan_pc090oj_sprite_ctrl_clear

    .global vdp_prepare_sprites
    .global vdp_commit_sprites
    .global vdp_commit_sprites_vram
    .global genesistan_pc090oj_dma_self_test

    .global pc090oj_object_ram
    .global pc090oj_candidate_bitset
    .global pc090oj_ctrl_shadow
    .global pc090oj_sprite_ctrl_shadow
    .global pc090oj_mirror_dirty
    .global pc090oj_candidate_count
    .global pc090oj_decoded_count
    .global pc090oj_code_zero_skipped_count
    .global pc090oj_blank_skipped_count
    .global pc090oj_unmapped_skipped_count
    .global pc090oj_offscreen_skipped_count
    .global pc090oj_drawable_count
    .global pc090oj_emitted_count
    .global pc090oj_dropped_count
    .global pc090oj_scan_colbank
    .global pc090oj_scan_active
    .global pc090oj_producer_oob_count
    .global pc090oj_producer_write_count

    .global staged_sprite_sat
    .global staged_sprite_descriptor_table
    .global staged_sprite_dirty
    .global staged_sprite_active_count
    .global sprite_tile_resident_code
    .global pc090oj_tile_dma_worklist
    .global pc090oj_tile_dma_count

    /* Build 0142 retained-identity translation state */
    .global pc090oj_workram_block_sprites
    .global pc090oj_workram_block_sprites_41f5e
    .global pc090oj_stage_block2c8
    .global record_to_slot
    .global represented_records
    .global waiting_records
    .global used_sat_slots
    .global worklist_entry_for_slot
    .global pc090oj_represented_count
    .global pc090oj_sat_dirty
    .global pc090oj_bootstrap_pending

    .global audit_guard_caller_pc
    .global audit_guard_register_snapshot
    .global audit_guard_fired_flag
    .global audit_guard_vcount
    .global audit_guard_heartbeat

    .global pc090oj_dma_test_fired_flag
    .global pc090oj_dma_test_mismatch_offset
    .global pc090oj_dma_test_expected_word
    .global pc090oj_dma_test_actual_word
    .global pc090oj_dma_test_actual_buffer
    .global pc090oj_dma_test_heartbeat

    .extern rastan_pc090oj
    .extern rastan_pc090oj_hud_white
    .extern pc090oj_slot_lut
    .extern genesistan_current_scene_id
    .equ    PC090OJ_SCENE_GAMEPLAY_ID, 1
    .extern palette_route_lookup
    /* Build 0208: PROUTE owner id for PC090OJ, matching the constant table in
     * palette_hooks.s (PROUTE_OWNER_PC090OJ = 3). */
    .equ    PROUTE_OWNER_PC090OJ_ID, 3
    .global pc090oj_hud_suppressed_count
    .extern pc090oj_blank_code_bitset
    .extern pc090oj_opaque_bbox
    .extern genesistan_hook_tilemap_bg_fill
    .extern genesistan_hook_tilemap_fg_fill
    .extern genesistan_hook_pc080sn_bg_scroll_fill
    .extern genesistan_hook_pc080sn_fg_scroll_fill

    .equ VDP_DATA,      0x00C00000
    .equ VDP_CTRL,      0x00C00004
    .equ SPRITE_TILE_BASE, 1024
    .equ ARCADE_ROM_BASE, 0x00000200
    .equ PC090OJ_HW_BASE, 0x00D00000
    /* Active mirrored HW window tracks the configured record count so that when
     * PC090OJ_MIRROR_RECORDS < 256 the address-based mirror writers reject
     * out-of-range records instead of overflowing the smaller mirror array. */
    .equ PC090OJ_HW_ACTIVE_END, (PC090OJ_HW_BASE + PC090OJ_MIRROR_BYTES)
    /* Arcade A5 work-RAM base.  Absolute arcade work-RAM pointers (0x0010Cxxx)
     * map to Genesis WRAM as a5 + (pointer - ARCADE_WORKRAM_A5_BASE); the Genesis
     * a5 (0x00FF0000) corresponds to this arcade base (arcade 0x0010C000 ->
     * Genesis 0x00FF0000, e.g. the ranking table names at 0x00FF0157). */
    .equ ARCADE_WORKRAM_A5_BASE, 0x0010C000
    /* Arcade 0x59F5E clears 8 PC090OJ records starting at HW 0x00D00048
     * (= PC090OJ_HW_BASE + record 9), i.e. records 9..16.  It never touches the
     * HIGH SCORE label records 4..8.  (Build 0149 fix: the translation cleared
     * records 0..7, wiping label records 4..7 on coin insertion -> only "RE"
     * remained above 273100.) */
    .equ HOOK_59F5E_CLEAR_FIRST_RECORD, 9   /* (0x00D00048 - PC090OJ_HW_BASE) / 8 */
    .equ HOOK_59F5E_CLEAR_RECORD_COUNT, 8
    .equ PC090OJ_BLOCK2C8_BASE_RECORD, 140
    .equ PC090OJ_BLOCK2C8_APPLIED_RECORDS, (8 * 10 + 19)
    .equ PC090OJ_BLOCK2C8_SCRATCH_RECORDS, 100
    .equ PC090OJ_BLOCK2C8_SCRATCH_BYTES, (PC090OJ_BLOCK2C8_SCRATCH_RECORDS * 8)
    .if PC090OJ_BLOCK2C8_APPLIED_RECORDS > PC090OJ_BLOCK2C8_SCRATCH_RECORDS
    .error "block A5+0x2C8 scratch too small"
    .endif
    .if (PC090OJ_BLOCK2C8_BASE_RECORD + PC090OJ_BLOCK2C8_APPLIED_RECORDS - 1) != 238
    .error "block A5+0x2C8 record span must end at record 238"
    .endif

    /* ------------------------------------------------------------------ *
     * Build 0147: PC090OJ viewport coordinate + opaque-clip constants.   *
     * Named so sprite/background alignment is easy to read and to tune   *
     * during later emulator, gameplay, and real-CRT testing.             *
     * ------------------------------------------------------------------ */
    /* 16x16 sprite cell geometry. */
    .equ PC090OJ_PATTERN_WIDTH,   16
    .equ PC090OJ_PATTERN_HEIGHT,  16
    .equ PC090OJ_PATTERN_MAX_ROW, 15    /* PC090OJ_PATTERN_HEIGHT - 1 */
    .equ PC090OJ_PATTERN_MAX_COL, 15    /* PC090OJ_PATTERN_WIDTH  - 1 */
    /* Arcade PC090OJ non-flipped coordinate inversion (MAME taito/pc090oj.cpp:
     * x = 320 - x - 16, y = 256 - y - 16 when the flip-screen ctrl bit is clear). */
    .equ PC090OJ_FLIP_X_TERM, 304       /* 320 - PC090OJ_PATTERN_WIDTH  */
    .equ PC090OJ_FLIP_Y_TERM, 240       /* 256 - PC090OJ_PATTERN_HEIGHT */
    /* Arcade -> Genesis display-origin alignment.  The background plane applies
     * VDP_DISPLAY_ORIGIN_Y_BIAS(=8) / _X_BIAS(=16) in vdp_comm.s so the arcade
     * visible-area origin (raster Y=8, per rastan.cpp set_visarea 8..247) maps to
     * Genesis display line 0.  Sprites use the SAME origin so sprite/background
     * stay vertically aligned; this also places the arcade top margin above the
     * Genesis viewport, where its records clip out naturally.  Configurable. */
    .equ PC090OJ_TO_GENESIS_Y_OFFSET, -8   /* = -VDP_DISPLAY_ORIGIN_Y_BIAS */
    .equ PC090OJ_TO_GENESIS_X_OFFSET,  0   /* frontend X already aligned; tune later */
    /* Effective sprite clip rectangle = intersection of the arcade visible area
     * (raster 8..247 -> Genesis 0..239 after the Y origin) and the Genesis output
     * viewport (0..223, 0..319).  The Genesis bounds bind; ends are exclusive. */
    .equ GENESIS_VIEWPORT_LEFT,   0
    .equ GENESIS_VIEWPORT_RIGHT,  320
    .equ GENESIS_VIEWPORT_TOP,    0
    .equ GENESIS_VIEWPORT_BOTTOM, 224
    /* Genesis SAT coordinate biases (SAT value = screen coord + bias). */
    .equ PC090OJ_SAT_Y_BIAS, 0x80
    .equ PC090OJ_SAT_X_BIAS, 0x80

/* ------------------------------------------------------------------------- */
/* Internal helpers                                                          */
/* ------------------------------------------------------------------------- */

/* d0=PC090OJ record index.  Candidate state is helper-derived; mirror remains truth. */

/* d2=byte offset inside the active 0x800-byte PC090OJ mirror. */

/* d6=PC090OJ record index.  Clear only after full-record code-zero decode. */

/* Legacy producer bridge (Build 0142): the unconverted per-site hooks publish
 * their arcade sprite record into the mirror and set the per-record candidate.
 * The staged SAT is no longer written here; it is rebuilt from the mirror by
 * .Lpc090oj_sync_record_from_mirror during VBlank (dirty candidates) so a single
 * retained renderer owns the SAT.  d0=record index; d1=word0,d2=Y,d3=code,d4=X.
 * Preserves d0-d4/d7 and a1..a6 for the calling producer loops.
 */
.Lpc090oj_emit_slot:
    movem.l %d5/%d6/%a0, -(%sp)
    cmpi.w  #256, %d0
    bhs.s   .Lpc090oj_emit_slot_oob
    move.w  %d0, %d6
    lsl.w   #3, %d6
    lea     pc090oj_object_ram, %a0
    adda.w  %d6, %a0
    move.w  %d1, (%a0)
    move.w  %d2, 2(%a0)
    move.w  %d3, 4(%a0)
    move.w  %d4, 6(%a0)
    addq.w  #1, pc090oj_producer_write_count
    movem.l (%sp)+, %d5/%d6/%a0
    rts
.Lpc090oj_emit_slot_oob:
    addq.w  #1, pc090oj_producer_oob_count
    movem.l (%sp)+, %d5/%d6/%a0
    rts


/* d0=slot clears slot */
.Lpc090oj_clear_slot:
    moveq   #0, %d1
    move.w  #0x0180, %d2
    moveq   #0, %d3
    moveq   #0, %d4
    moveq   #0, %d5
    moveq   #0, %d6
    moveq   #0, %d7
    bsr     .Lpc090oj_emit_slot
    rts

/* A1=PC090OJ HW address, D0=word value.  Writes only the active 0x800-byte mirror. */
.Lpc090oj_mirror_write_word_a1_d0:
    move.l  %a2, -(%sp)
    move.l  %a1, %d2
    cmpi.l  #PC090OJ_HW_BASE, %d2
    blo.s   .Lpc090oj_mirror_word_oob
    cmpi.l  #PC090OJ_HW_ACTIVE_END, %d2
    bhs.s   .Lpc090oj_mirror_word_oob
    subi.l  #PC090OJ_HW_BASE, %d2
    lea     pc090oj_object_ram, %a2
    adda.l  %d2, %a2
    move.w  %d0, (%a2)
    addq.w  #1, pc090oj_producer_write_count
    move.l  (%sp)+, %a2
    rts
.Lpc090oj_mirror_word_oob:
    addq.w  #1, pc090oj_producer_oob_count
    move.l  (%sp)+, %a2
    rts

/* A1=PC090OJ HW address, D0=byte value.  Used for 0x3B802 byte stores. */
.Lpc090oj_mirror_write_byte_a1_d0:
    move.l  %a2, -(%sp)
    move.l  %a1, %d2
    cmpi.l  #PC090OJ_HW_BASE, %d2
    blo.s   .Lpc090oj_mirror_byte_oob
    cmpi.l  #PC090OJ_HW_ACTIVE_END, %d2
    bhs.s   .Lpc090oj_mirror_byte_oob
    subi.l  #PC090OJ_HW_BASE, %d2
    lea     pc090oj_object_ram, %a2
    adda.l  %d2, %a2
    move.b  %d0, (%a2)
    addq.w  #1, pc090oj_producer_write_count
    move.l  (%sp)+, %a2
    rts
.Lpc090oj_mirror_byte_oob:
    addq.w  #1, pc090oj_producer_oob_count
    move.l  (%sp)+, %a2
    rts

/* Converted semantic family (Build 0142): the complete 22-object work-RAM block
 * shared by arcade 0x041DAE / 0x041F5E / 0x045DFA.  Block A = 18 records at
 * A5+0x11B2, block B = 4 records at A5+0x0170; tuple = {word0, Y, code, X}.
 * Each record is written once into the mirror (exact arcade store), then
 * synchronized directly from the mirror and its superseded candidate cleared.
 * It does NOT set a candidate; later unconverted writes to the same record
 * re-set the candidate and VBlank re-syncs it (§9-E.2/§9-E.3).
 */
/* 0x041F5E path (KF-044 companion): the original arcade routine copies
 *   lea 0x11B2(a5),a0 ; moveq #18 ; lea 0xD003C0,a1   (0xD003C0/8 = record 120)
 *   lea 0x0170(a5),a0 ; moveq #4  ; lea 0xD002E0,a1   (0xD002E0/8 = record 92)
 * so block A -> records 120..137 and block B -> records 92..95.  The previous
 * translation collapsed both blocks to records 0..17 / 18..21, so the player
 * PC090OJ cluster (which the represent engine reads from the arcade-correct
 * records) was never populated.  Restore the arcade destination records. */
pc090oj_workram_block_sprites_41f5e:
    movem.l %d0-%d7/%a0-%a6, -(%sp)
    move.w  #120, %d5                    /* block A base record (0xD003C0/8) */
    move.w  #92, %d7                     /* block B base record (0xD002E0/8) */
    bra.s   .Lwbs_run

/* Default path: arcade 0x045DFA hook and any legacy caller keep the prior
 * mapping (block A -> 0..17, block B -> 18..21).  Arcade 0x045DFA is a distinct
 * routine (sources A5+0x5C8/0x748/0x8C8, dest records 140/46/96 via 0x3D054),
 * so its true destination is out of this fix's proven scope -- unchanged. */
pc090oj_workram_block_sprites:
    movem.l %d0-%d7/%a0-%a6, -(%sp)
    move.w  #0, %d5
    move.w  #18, %d7
.Lwbs_run:
    lea     0x11B2(%a5), %a0
    move.w  %d5, %d0                     /* d0 = block A base record */
    move.w  %d5, %d6
    addi.w  #18, %d6                     /* d6 = block A end (exclusive) */
.Lwbs_block_a:
    move.w  (%a0), %d1
    move.w  2(%a0), %d2
    move.w  4(%a0), %d3
    move.w  6(%a0), %d4
    bsr     .Lpc090oj_family_apply_record
    adda.w  #8, %a0
    addq.w  #1, %d0
    cmp.w   %d6, %d0
    blo.s   .Lwbs_block_a

    lea     0x0170(%a5), %a0
    move.w  %d7, %d0                     /* d0 = block B base record */
    move.w  %d7, %d6
    addi.w  #4, %d6                      /* d6 = block B end (exclusive) */
.Lwbs_block_b:
    move.w  (%a0), %d1
    move.w  2(%a0), %d2
    move.w  4(%a0), %d3
    move.w  6(%a0), %d4
    bsr     .Lpc090oj_family_apply_record
    adda.w  #8, %a0
    addq.w  #1, %d0
    cmp.w   %d6, %d0
    blo.s   .Lwbs_block_b
    movem.l (%sp)+, %d0-%d7/%a0-%a6
    rts

/* d0=record, d1=word0, d2=Y, d3=code, d4=X.  Write the mirror once, then sync
 * from the mirror and clear the superseded candidate, inside a VINT-masked
 * critical section so a VBlank commit never observes a half-applied structural
 * change (§9-C interrupt safety).
 */
/* d0=record, d1..d4 = tuple.  N1: plain object-table write (no candidates,
 * no compare, no interrupt masking -- matches arcade object-RAM semantics). */
.Lpc090oj_family_apply_record:
    movem.l %d5-%d6/%a0, -(%sp)
    cmpi.w  #256, %d0
    bhs.s   .Lpc090oj_far_oob
    move.w  %d0, %d6
    lsl.w   #3, %d6
    lea     pc090oj_object_ram, %a0
    adda.w  %d6, %a0
    move.w  %d1, (%a0)
    move.w  %d2, 2(%a0)
    move.w  %d3, 4(%a0)
    move.w  %d4, 6(%a0)
    addq.w  #1, pc090oj_producer_write_count
    movem.l (%sp)+, %d5-%d6/%a0
    rts
.Lpc090oj_far_oob:
    addq.w  #1, pc090oj_producer_oob_count
    movem.l (%sp)+, %d5-%d6/%a0
    rts


/* ------------------------------------------------------------------------- */
/* 17 helpers                                                                */
/* ------------------------------------------------------------------------- */

/* Build 0146 faithful translation of arcade 0x03B902.
 * Arcade body: lea 0xD00088,%a1 (records 17..21); tst.w %d1; bne fill.
 *   clear path (d1==0): lea 0x3B984,%a0; moveq #5,%d1; bsr 0x3B930   -> copy the
 *     5-record table at arcade 0x3B984 (Genesis 0x3BB84) into records 17..21.
 *   fill path  (d1!=0): move.b %d1,2(%a1); addq.l #8,%a1  x5  -> write the byte
 *     d1 to the Y-high byte (offset 2) of records 17..21 only.
 * The prior Build 0142-era body wrote full descriptors to records 0..4, which
 * clobbered record 4 (the HIGH SCORE "GH" glyph) that the arcade never touches.
 * Registers are fully preserved (movem), matching the prior helper's contract.
 */
genesistan_pc090oj_hook_target_3b902:
    movem.l %d0-%d7/%a0-%a6, -(%sp)
    tst.w   %d1
    bne.s   .Lhook_3b902_fill
    /* clear path: table copy into records 17..21 via the faithful 0x3B930 helper */
    lea     0x00D00088, %a1
    lea     0x0003BB84, %a0                 /* arcade 0x3B984 table, +0x200 */
    moveq   #5, %d1
    bsr     genesistan_pc090oj_hook_target_3b930
    bra.s   .Lhook_3b902_done
.Lhook_3b902_fill:
    /* fill path: write byte d1 to the Y-high byte (offset 2) of records 17..21 */
    lea     0x00D0008A, %a1                 /* 0xD00088 + 2 (record 17 Y-high) */
    moveq   #5, %d5
.Lhook_3b902_fill_loop:
    move.w  %d1, %d0
    bsr     .Lpc090oj_mirror_write_byte_a1_d0
    adda.l  #8, %a1
    subq.w  #1, %d5
    bne.s   .Lhook_3b902_fill_loop
.Lhook_3b902_done:
    movem.l (%sp)+, %d0-%d7/%a0-%a6
    rts

genesistan_pc090oj_hook_target_3b926:
    movem.l %d0-%d7/%a0-%a6, -(%sp)
    moveq   #5, %d0
.Lhook_3b926_loop:
    bsr     .Lpc090oj_clear_slot
    addq.w  #1, %d0
    cmpi.w  #14, %d0
    blo.s   .Lhook_3b926_loop
    movem.l (%sp)+, %d0-%d7/%a0-%a6
    rts

genesistan_pc090oj_hook_target_3b930:
    movem.l %d0-%d7/%a0-%a6, -(%sp)
    move.w  %d1, %d6
.Lhook_3b930_loop:
    tst.w   %d6
    beq.s   .Lhook_3b930_done

    moveq   #0, %d0                  /* word0 = 0 */
    bsr     .Lpc090oj_mirror_write_word_a1_d0
    addq.l  #2, %a1

    moveq   #0, %d0                  /* word1 = zero-extended Y byte */
    move.b  (%a0)+, %d0
    bsr     .Lpc090oj_mirror_write_word_a1_d0
    addq.l  #2, %a1

    moveq   #0, %d0                  /* word2 = zero-extended code byte */
    move.b  (%a0)+, %d0
    bsr     .Lpc090oj_mirror_write_word_a1_d0
    addq.l  #2, %a1

    move.w  (%a0)+, %d7              /* word3 = transformed X word */
    jsr     (0x0005B712).l
    move.w  %d7, %d0
    bsr     .Lpc090oj_mirror_write_word_a1_d0
    addq.l  #2, %a1

    subq.w  #1, %d6
    bra.s   .Lhook_3b930_loop
.Lhook_3b930_done:
    movem.l (%sp)+, %d0-%d7/%a0-%a6
    rts

/* Build 0192: hook_target_41dae / hook_target_45dfa replace arcade routines
 * 0x041DAE / 0x045DFA, which do NOT copy A5+0x11B2 (they copy A5+0x508 / A5+0x5C8
 * to records 57/96/140/46 via 0x3D054).  The current Genesis default helper
 * instead copies the PLAYER block A5+0x11B2 -> records 0..17 (and A5+0x0170 ->
 * 18..21), which are exact duplicates of what hook_target_41f5e already stages to
 * the arcade-canonical records 120..137 / 92..95.  In Stage 1 gameplay the arcade
 * records 0..17 are empty, so this low copy is a proven Genesis-only spurious
 * duplicate that draws Rastan twice and wastes ~half the SAT budget.  Suppress it
 * in gameplay only (scene 1); other scenes keep the existing behavior since the
 * low copy has not been proven spurious there. */
genesistan_pc090oj_hook_target_41dae:
    cmpi.b  #PC090OJ_SCENE_GAMEPLAY_ID, genesistan_current_scene_id
    beq.s   .Lhook_41dae_gameplay_record46
    bsr     pc090oj_workram_block_sprites
    rts
.Lhook_41dae_gameplay_record46:
    bsr     pc090oj_stage_block2c8
    bsr     .Lpc090oj_stage_record46_validated
    bsr     pc090oj_native_emit_pass    /* N1: last gameplay producer -> emit */
    rts

genesistan_pc090oj_hook_target_41f5e:
    bsr     pc090oj_workram_block_sprites_41f5e
    rts

genesistan_pc090oj_hook_target_45dfa:
    cmpi.b  #PC090OJ_SCENE_GAMEPLAY_ID, genesistan_current_scene_id
    beq.s   .Lhook_45dfa_skip
    bsr     pc090oj_workram_block_sprites
.Lhook_45dfa_skip:
    rts

/* Build 0204 / OPEN-017: faithfully re-enable the first gameplay enemy block
 * only.  Arcade 0x41E76..0x41EB4 walks A5+0x748 for 11 entries, destination
 * record 46, and calls 0x3D054 with d2=1 after loading d0/d6/d7 from the actor.
 * Keep the Build 0203 safety gate (active, nonzero code, a4+0x36 clear), call
 * the relocated engine into an 8-byte scratch record, and flush only nonzero
 * output tuples into the normal mirror/candidate path. */
.Lpc090oj_stage_record46_validated:
    movem.l %d0-%d7/%a0-%a6, -(%sp)

    lea     0x0748(%a5), %a4
    move.w  #46, .Lrecord46_rec         /* current destination record */
    move.w  #10, .Lrecord46_count       /* 11 actors */

.Lrecord46_loop:
    tst.b   0(%a4)
    beq.s   .Lrecord46_next
    tst.b   1(%a4)
    beq.s   .Lrecord46_next
    tst.b   0x36(%a4)
    bne.s   .Lrecord46_next

    lea     .Lrecord46_scratch, %a1
    clr.l   (%a1)
    clr.l   4(%a1)

    move.b  1(%a4), %d0
    move.b  32(%a4), %d6
    move.b  2(%a4), %d7
    moveq   #1, %d2
    jsr     0x0003D254

    lea     .Lrecord46_scratch, %a0
    move.w  4(%a0), %d3                 /* code word */
    beq.s   .Lrecord46_next             /* never flush code-0 scratch output */
    move.w  (%a0), %d1
    move.w  2(%a0), %d2
    move.w  6(%a0), %d4
    move.w  .Lrecord46_rec, %d0
    bsr     .Lpc090oj_family_apply_record

.Lrecord46_next:
    adda.w  #64, %a4
    addq.w  #1, .Lrecord46_rec
    subq.w  #1, .Lrecord46_count
    bpl     .Lrecord46_loop

    movem.l (%sp)+, %d0-%d7/%a0-%a6
    rts

/* N1: block A5+0x2C8 -> object-table rows 140..238 DIRECTLY (arcade 0x41E22
 * semantics: d2=10, 19 for entry 8; engine writes exactly d2 rows via (A1)+).
 * KF-067 -8 vertical correction applied to the rows each engine call emits.
 * Deferred-special (a4@(3)!=0) and code-zero entries preserve their rows. */
pc090oj_stage_block2c8:
    movem.l %d0-%d7/%a0-%a6, -(%sp)
    lea     pc090oj_object_ram + (PC090OJ_BLOCK2C8_BASE_RECORD * 8), %a1
    lea     0x02C8(%a5), %a4
    moveq   #0, %d5
.Lb2c8_entry:
    moveq   #10, %d2
    cmpi.w  #8, %d5
    bne.s   .Lb2c8_d2ok
    moveq   #19, %d2
.Lb2c8_d2ok:
    tst.b   0(%a4)
    beq.s   .Lb2c8_blank
    tst.b   5(%a4)
    beq.s   .Lb2c8_blank
    tst.b   3(%a4)
    bne.s   .Lb2c8_skip
    tst.b   1(%a4)
    beq.s   .Lb2c8_skip
    move.b  1(%a4), %d0
    move.b  32(%a4), %d6
    move.b  2(%a4), %d7
    move.w  %d2, -(%sp)                 /* engine clobbers d0-d7 (KF-067) */
    jsr     0x0003D254
    move.w  (%sp)+, %d0
    subq.w  #1, %d0
    movea.l %a1, %a0
.Lb2c8_yfix:
    suba.w  #8, %a0
    move.w  2(%a0), %d1
    move.w  %d1, %d4
    andi.w  #0x01FF, %d1
    subq.w  #8, %d1
    andi.w  #0x01FF, %d1
    andi.w  #0xFE00, %d4
    or.w    %d4, %d1
    move.w  %d1, 2(%a0)
    dbra    %d0, .Lb2c8_yfix
    bra.s   .Lb2c8_next
.Lb2c8_blank:
    move.w  %d2, %d0
    subq.w  #1, %d0
.Lb2c8_blankloop:
    move.w  #0x0180, 2(%a1)
    adda.w  #8, %a1
    dbra    %d0, .Lb2c8_blankloop
    bra.s   .Lb2c8_next
.Lb2c8_skip:
    move.w  %d2, %d0
    lsl.w   #3, %d0
    adda.w  %d0, %a1
.Lb2c8_next:
    adda.w  #64, %a4
    addq.w  #1, %d5
    cmpi.w  #9, %d5
    blo     .Lb2c8_entry
    movem.l (%sp)+, %d0-%d7/%a0-%a6
    rts


genesistan_pc090oj_hook_target_59f5e:
    movem.l %d0-%d7/%a0-%a6, -(%sp)

    moveq   #HOOK_59F5E_CLEAR_FIRST_RECORD, %d0
.Lhook_59f5e_clear_slots:
    bsr     .Lpc090oj_clear_slot
    addq.w  #1, %d0
    cmpi.w  #(HOOK_59F5E_CLEAR_FIRST_RECORD + HOOK_59F5E_CLEAR_RECORD_COUNT), %d0
    blo.s   .Lhook_59f5e_clear_slots

    /* preserve arcade workram tuple writes at A5+0x0170 */
    lea     0x0170(%a5), %a0
    moveq   #3, %d1
.Lhook_59f5e_workram_loop:
    move.w  #0x0080, (%a0)+
    move.w  #0x0000, (%a0)+
    move.w  #0x0000, (%a0)+
    move.w  #0x0000, (%a0)+
    dbra    %d1, .Lhook_59f5e_workram_loop

    movem.l (%sp)+, %d0-%d7/%a0-%a6
    rts

/* PC090OJ ctrl register (word offset 0x0DFF / HW 0x00D01BFE).
 * Bit 0 is the global-flip control (a change flips every sprite on/off screen),
 * so an actual change reevaluates all 256 records by requesting a full
 * candidate sweep processed at the next VBlank (§9-E.4).
 */
genesistan_pc090oj_ctrl_set_1:
    cmpi.w  #1, pc090oj_ctrl_shadow
    beq.s   .Lctrl_set_1_done
    move.w  #1, pc090oj_ctrl_shadow
.Lctrl_set_1_done:
    rts

genesistan_pc090oj_ctrl_set_0:
    tst.w   pc090oj_ctrl_shadow
    beq.s   .Lctrl_set_0_done
    clr.w   pc090oj_ctrl_shadow
.Lctrl_set_0_done:
    rts

/* External sprite_ctrl at HW 0x00380000.  D0 holds the arcade value; its colour
 * bank feeds sprite palette selection.  On an actual change, reevaluate (a full
 * sweep is a safe superset of the represented-only palette refresh).
 */
genesistan_pc090oj_sprite_ctrl_write_d0:
    cmp.w   pc090oj_sprite_ctrl_shadow, %d0
    beq.s   .Lsprite_ctrl_write_done
    move.w  %d0, pc090oj_sprite_ctrl_shadow
.Lsprite_ctrl_write_done:
    rts

genesistan_pc090oj_sprite_ctrl_clear:
    tst.w   pc090oj_sprite_ctrl_shadow
    beq.s   .Lsprite_ctrl_clear_done
    clr.w   pc090oj_sprite_ctrl_shadow
.Lsprite_ctrl_clear_done:
    rts

genesistan_hook_3ad44_dispatch:
    movem.l %d0-%d7/%a0-%a6, -(%sp)

    /* A0 dispatch:
     *   tilemap: [0x00C00000,0x00C10000)
     *   PC090OJ: [0x00D00000,0x00D00800)
     *   else:    audit fall-through
     */
    move.l  %a0, %d2
    cmpi.l  #0x00C00000, %d2
    blo.s   .Lhook_3ad44_check_pc090oj
    cmpi.l  #0x00C10000, %d2
    blo.s   .Lhook_3ad44_tilemap

.Lhook_3ad44_check_pc090oj:
    cmpi.l  #0x00D00000, %d2
    blo     .Lhook_3ad44_audit
    cmpi.l  #0x00D00800, %d2
    bhs     .Lhook_3ad44_audit

    /* PC090OJ branch: preserve the arcade long-fill into active object RAM. */
    move.l  %a0, %d2
    subi.l  #0x00D00000, %d2
    bmi     .Lhook_3ad44_finish
    cmpi.l  #0x00000800, %d2
    bhs     .Lhook_3ad44_finish

    lea     pc090oj_object_ram, %a1
    adda.l  %d2, %a1
    move.w  %d1, %d3
.Lhook_3ad44_pc090oj_long_fill_loop:
    tst.w   %d3
    beq     .Lhook_3ad44_finish
    cmpi.l  #0x00000800, %d2
    bhs     .Lhook_3ad44_finish
    swap    %d0
    move.w  %d0, (%a1)+
    swap    %d0
    addq.l  #2, %d2
    cmpi.l  #0x00000800, %d2
    bhs     .Lhook_3ad44_finish
    move.w  %d0, (%a1)+
    addq.l  #2, %d2
    subq.w  #1, %d3
    bra.s   .Lhook_3ad44_pc090oj_long_fill_loop

.Lhook_3ad44_tilemap:
    cmpi.l  #0x00C04000, %d2
    blo.s   .Lhook_3ad44_bg_names
    cmpi.l  #0x00C08000, %d2
    blo.s   .Lhook_3ad44_bg_scroll
    cmpi.l  #0x00C0C000, %d2
    blo.s   .Lhook_3ad44_fg_names
    bsr     genesistan_hook_pc080sn_fg_scroll_fill
    bra     .Lhook_3ad44_finish

.Lhook_3ad44_bg_names:
    bsr     genesistan_hook_tilemap_bg_fill
    bra     .Lhook_3ad44_finish

.Lhook_3ad44_bg_scroll:
    bsr     genesistan_hook_pc080sn_bg_scroll_fill
    bra     .Lhook_3ad44_finish

.Lhook_3ad44_fg_names:
    bsr     genesistan_hook_tilemap_fg_fill
    bra     .Lhook_3ad44_finish

.Lhook_3ad44_audit:
    /* Reuse §7.3 audit-guard capture + heartbeat halt loop. */
    move.l  60(%sp), %d0
    move.l  %d0, audit_guard_caller_pc

    lea     audit_guard_register_snapshot, %a1
    moveq   #(15 - 1), %d0
.Lhook_3ad44_snap:
    move.l  (%sp,%d0.w*4), %d1
    move.l  %d1, (%a1)+
    dbra    %d0, .Lhook_3ad44_snap

    move.w  0x00C00008, audit_guard_vcount
    move.w  #0x3AD4, audit_guard_fired_flag
    bra     .Lag_halt_loop

.Lhook_3ad44_finish:
    movem.l (%sp)+, %d0-%d7/%a0-%a6
    rts

genesistan_pc090oj_hook_init_priority_3ad84:
    movem.l %d0-%d7/%a0-%a6, -(%sp)

    move.w  10*2(%a5), %d7
    andi.w  #0x00E0, %d7
    lsr.w   #1, %d7

    moveq   #76, %d0
    moveq   #0, %d1
    move.w  #0x00C8, %d2
    moveq   #0, %d3
    move.w  #0x0160, %d4
    moveq   #0, %d5
    moveq   #0x0002, %d6            /* priority-ladder gate bit */
.Lhook_3ad84_loop:
    bsr     .Lpc090oj_emit_slot
    addi.w  #0x0010, %d2
    addq.w  #1, %d0
    cmpi.w  #80, %d0
    blo.s   .Lhook_3ad84_loop

    movem.l (%sp)+, %d0-%d7/%a0-%a6
    rts

genesistan_pc090oj_hook_score_digit_3b802:
    movem.l %d0-%d7/%a0-%a6, -(%sp)

    /* Preserve arcade structure at 0x3B802: record = 10 bytes at 0x3B87E+mode*10 */
    clr.l   %d5
    movea.l %d5, %a6                 /* leading-zero state */

    mulu.w  #10, %d0
    lea     .Lhook_3b802_record_table, %a0
    adda.w  %d0, %a0

    clr.w   %d0
    move.b  (%a0), %d0               /* digit count */
    cmpi.w  #1, %d0
    bne.s   .Lhook_3b802_count_ready
    moveq   #1, %d5
    movea.l %d5, %a6
.Lhook_3b802_count_ready:
    move.b  1(%a0), %d6              /* Y low-byte source */
    movea.l 2(%a0), %a4              /* arcade PC090OJ destination pointer */
    movea.l 6(%a0), %a2              /* arcade score-data source pointer */

    /* Score-source pointers in the record table are absolute arcade work-RAM
     * addresses anchored at the arcade A5 base (0x0010C000).  The Genesis holds
     * the same work-RAM anchored at its own A5 (0x00FF0000), so the mapped
     * address is a5 + (source - ARCADE_WORKRAM_A5_BASE).  (Build 0148 fix: the
     * base was 0x00100000, which read 0xC000 past the real values -> zeros.) */
    move.l  %a2, %d2
    subi.l  #ARCADE_WORKRAM_A5_BASE, %d2
    movea.l %a5, %a2
    adda.l  %d2, %a2

    moveq   #0, %d3
    move.w  %d0, %d3
    movea.l %d3, %a3                 /* loop counter */

.Lhook_3b802_loop:
    move.l  %a3, %d2
    tst.w   %d2
    beq     .Lhook_3b802_done

    btst    #0, %d2
    beq.s   .Lhook_3b802_even_nibble

    moveq   #0, %d1
    move.b  (%a2), %d1
    andi.w  #0x000F, %d1
    bsr     .Lhook_3b802_visflag
    addi.w  #0x002A, %d1
    subq.l  #1, %a2
    bra.s   .Lhook_3b802_emit

.Lhook_3b802_even_nibble:
    moveq   #0, %d1
    move.b  (%a2), %d1
    lsr.b   #4, %d1
    andi.w  #0x000F, %d1
    bsr     .Lhook_3b802_visflag
    addi.w  #0x002A, %d1

.Lhook_3b802_emit:
    /* Preserve arcade destination writes: byte to +2/+3, digit word to +4. */
    movea.l %a4, %a1
    adda.w  #2, %a1
    move.w  %d4, %d0
    bsr     .Lpc090oj_mirror_write_byte_a1_d0

    movea.l %a4, %a1
    adda.w  #3, %a1
    moveq   #0, %d0
    move.b  %d6, %d0
    bsr     .Lpc090oj_mirror_write_byte_a1_d0

    movea.l %a4, %a1
    adda.w  #4, %a1
    move.w  %d1, %d0
    bsr     .Lpc090oj_mirror_write_word_a1_d0

.Lhook_3b802_next:
    subq.l  #8, %a4
    subq.l  #1, %a3
    bra     .Lhook_3b802_loop

.Lhook_3b802_done:
    movem.l (%sp)+, %d0-%d7/%a0-%a6
    rts

.Lhook_3b802_visflag:
    move.l  %a6, %d5
    bne.s   .Lhook_3b802_vis_nonzero
    tst.w   %d1
    bne.s   .Lhook_3b802_vis_nonzero
    moveq   #1, %d4                   /* leading zero */
    rts

.Lhook_3b802_vis_nonzero:
    moveq   #1, %d5
    movea.l %d5, %a6
    moveq   #0, %d4
    rts

.Lhook_3b802_record_table:
    .byte 0x06,0x10,0x00,0xD0,0x01,0x08,0x00,0x10,0xC1,0x1E
    .byte 0x06,0x10,0x00,0xD0,0x01,0x50,0x00,0x10,0xC1,0x1E
    .byte 0x06,0x10,0x00,0xD0,0x00,0xD8,0x00,0x10,0xC1,0x42
    .byte 0x01,0xE8,0x00,0xD0,0x00,0xA8,0x00,0x10,0xC1,0x17
    .byte 0x01,0xE4,0x00,0xD0,0x00,0x88,0x00,0x10,0xC1,0x03
    .align 2

genesistan_pc090oj_hook_slot_init_54052:
    movem.l %d0-%d7/%a0-%a6, -(%sp)

    /* Phase A text-RAM clear loops replicated verbatim */
    movea.l #0x0010D1D2, %a1
    move.w  #6, %d2
.Lhook_54052_loop1:
    move.w  #3, (%a1)+
    move.w  #0, (%a1)+
    move.w  #0, (%a1)+
    move.w  #0, (%a1)+
    subq.w  #1, %d2
    bne.s   .Lhook_54052_loop1

    move.w  #4, %d2
    movea.l #0x0010D1B2, %a1
.Lhook_54052_loop2:
    move.w  #3, (%a1)+
    move.w  #0, (%a1)+
    move.w  #0, (%a1)+
    move.w  #0, (%a1)+
    subq.w  #1, %d2
    bne.s   .Lhook_54052_loop2

    movea.l #0x0010D1F2, %a1
    move.w  #6, %d2
.Lhook_54052_loop3:
    move.w  #3, (%a1)+
    move.w  #0, (%a1)+
    move.w  #0, (%a1)+
    move.w  #0, (%a1)+
    subq.w  #1, %d2
    bne.s   .Lhook_54052_loop3

    move.w  10*2(%a5), %d7
    andi.w  #0x00E0, %d7
    lsr.w   #1, %d7

    moveq   #72, %d0
.Lhook_54052_emit:
    move.w  #0x0003, %d1
    move.w  #0x0000, %d2
    move.w  #0x0000, %d3
    move.w  #0x0000, %d4
    moveq   #0, %d5
    moveq   #0, %d6
    bsr     .Lpc090oj_emit_slot
    addq.w  #1, %d0
    cmpi.w  #76, %d0
    blo.s   .Lhook_54052_emit

    movem.l (%sp)+, %d0-%d7/%a0-%a6
    rts

genesistan_pc090oj_hook_sprite_update_54810:
    movem.l %d0-%d7/%a0-%a6, -(%sp)

    move.w  10*2(%a5), %d7
    andi.w  #0x00E0, %d7
    lsr.w   #1, %d7

    movea.l #ARCADE_ROM_BASE+0x0005DA5E, %a0
    mulu.w  #24, %d0
    adda.w  %d0, %a0

    moveq   #44, %d0
    moveq   #4, %d6
.Lhook_54810_loop:
    move.w  4(%a0), %d1

    moveq   #0, %d2
    move.b  3(%a0), %d2
    ext.w   %d2
    add.w   0x129C(%a5), %d2
    addq.w  #1, %d2
    andi.w  #0x01FF, %d2

    move.w  (%a0), %d3

    moveq   #0, %d4
    move.b  2(%a0), %d4
    ext.w   %d4
    add.w   0x129A(%a5), %d4
    andi.w  #0x01FF, %d4

    moveq   #0, %d5
    move.w  %d6, -(%sp)              /* save loop counter */
    moveq   #0, %d6
    bsr     .Lpc090oj_emit_slot
    move.w  (%sp)+, %d6              /* restore loop counter */

    adda.w  #6, %a0
    addq.w  #1, %d0
    subq.w  #1, %d6
    bne.s   .Lhook_54810_loop

    movem.l (%sp)+, %d0-%d7/%a0-%a6
    rts

genesistan_pc090oj_hook_sprite_decay_5607c:
    movem.l %d0-%d7/%a0-%a6, -(%sp)

    move.w  0x1392(%a5), %d0
    andi.w  #0x0003, %d0
    bne.s   .Lhook_5607c_done

    clr.w   0x10AE(%a5)
    clr.w   0x10B0(%a5)

    moveq   #56, %d0
.Lhook_5607c_loop:
    cmpi.w  #64, %d0
    bhs.s   .Lhook_5607c_done

    move.w  %d0, %d1
    mulu.w  #12, %d1
    lea     staged_sprite_descriptor_table, %a0
    adda.l  %d1, %a0

    btst    #0, (%a0)
    beq.s   .Lhook_5607c_next

    move.w  2(%a0), %d2
    subq.w  #1, %d2
    andi.w  #0x01FF, %d2
    move.w  %d2, 2(%a0)

    move.w  6(%a0), %d1
    move.w  8(%a0), %d3
    move.w  4(%a0), %d4
    cmpi.w  #0x0010, %d2
    bne.s   .Lhook_5607c_keep_tile
    clr.w   %d3
    move.w  %d3, 8(%a0)
.Lhook_5607c_keep_tile:
    moveq   #0, %d5
    moveq   #0, %d6
    move.w  10*2(%a5), %d7
    andi.w  #0x00E0, %d7
    lsr.w   #1, %d7
    bsr     .Lpc090oj_emit_slot

.Lhook_5607c_next:
    addq.w  #1, %d0
    bra.s   .Lhook_5607c_loop

.Lhook_5607c_done:
    movem.l (%sp)+, %d0-%d7/%a0-%a6
    rts

genesistan_pc090oj_hook_copy_56114:
    movem.l %d0-%d7/%a0-%a6, -(%sp)

    move.w  10*2(%a5), %d7
    andi.w  #0x00E0, %d7
    lsr.w   #1, %d7

    moveq   #64, %d0
.Lhook_56114_loop:
    cmpi.w  #68, %d0
    bhs.s   .Lhook_56114_done
    move.w  (%a0), %d1
    cmpi.w  #-1, %d1
    beq.s   .Lhook_56114_done
    move.w  2(%a0), %d2
    move.w  4(%a0), %d3
    move.w  6(%a0), %d4
    moveq   #0, %d5
    moveq   #0, %d6
    bsr     .Lpc090oj_emit_slot
    adda.w  #8, %a0
    addq.w  #1, %d0
    bra.s   .Lhook_56114_loop

.Lhook_56114_done:
    movem.l (%sp)+, %d0-%d7/%a0-%a6
    rts

genesistan_pc090oj_hook_zero_fill_56440:
    movem.l %d0-%d7/%a0-%a6, -(%sp)

    moveq   #68, %d0
.Lhook_56440_loop:
    cmpi.w  #72, %d0
    bhs.s   .Lhook_56440_done
    bsr     .Lpc090oj_clear_slot
    addq.w  #1, %d0
    bra.s   .Lhook_56440_loop

.Lhook_56440_done:
    movem.l (%sp)+, %d0-%d7/%a0-%a6
    rts

genesistan_pc090oj_hook_status_sprite_5a098:
    movem.l %d0-%d7/%a0-%a6, -(%sp)

    move.w  10*2(%a5), %d7
    andi.w  #0x00E0, %d7
    lsr.w   #1, %d7

    moveq   #30, %d0
    move.w  #0x0010, %d4
.Lhook_5a098_loop:
    cmpi.w  #44, %d0
    bhs.s   .Lhook_5a098_done
    moveq   #0, %d1
    move.w  #0x00E8, %d2
    move.w  %d0, %d3
    addi.w  #0x03CA, %d3
    moveq   #0, %d5
    moveq   #0, %d6
    bsr     .Lpc090oj_emit_slot
    addi.w  #0x0010, %d4
    addq.w  #1, %d0
    bra.s   .Lhook_5a098_loop

.Lhook_5a098_done:
    movem.l (%sp)+, %d0-%d7/%a0-%a6
    rts

genesistan_pc090oj_hook_audit_guard:
    movem.l %d0-%d7/%a0-%a6, -(%sp)

    /* return address for invoking site */
    move.l  60(%sp), %d0
    move.l  %d0, audit_guard_caller_pc

    /* snapshot registers (d0-d7,a0-a6 = 15 longs) */
    lea     audit_guard_register_snapshot, %a1
    moveq   #(15 - 1), %d0
.Lag_snap:
    move.l  (%sp,%d0.w*4), %d1
    move.l  %d1, (%a1)+
    dbra    %d0, .Lag_snap

    move.w  0x00C00008, audit_guard_vcount
    move.w  #0x510E, audit_guard_fired_flag

.Lag_halt_loop:
    move.b  audit_guard_heartbeat, %d0
    addq.b  #1, %d0
    move.b  %d0, audit_guard_heartbeat
    bra     .Lag_halt_loop

/* ------------------------------------------------------------------------- */
/* VBlank sprite prepare / commit split                                      */

/* ========================================================================= */
/* N1 native sprite pipeline (Build 0219): object table -> shadow SAT.       */
/*                                                                           */
/* The 256-row object table (pc090oj_object_ram) is the arcade program's own */
/* persistent slot-addressed sprite store: incremental producers (score,     */
/* status, decay, copy hooks) update rows in place exactly as arcade code    */
/* updated PC090OJ RAM.  Once per frame ONE ascending pass emits final       */
/* Genesis SAT entries into a double-buffered shadow SAT.  Ascending row     */
/* order = PC090OJ paint priority (MAME pc090oj draws descending, so record  */
/* 0 lands on top; Genesis link order gives the same result).  Retirement is */
/* implicit: rows the producers cleared/blanked simply emit nothing.         */
/* No mirror shadow, no candidates, no representation/eviction engine, no   */
/* record->slot map, no VBlank record scans in gameplay (the pass runs at    */
/* the end of the arcade's own sprite dispatcher; frontend scenes fall back  */
/* to a VBlank pass).  Residency is code-keyed, 64 sets x 2 ways over 128    */
/* VRAM cells (tiles 1024..1535), so SAT position changes never re-upload.  */
/* ========================================================================= */
    .equ NATIVE_SAT_MAX, 80
    .equ NATIVE_CELLS, 128

/* d1=word0, d7=colbank -> d0 = Genesis palette line (Build 0210 semantics). */
.Lnative_palsel:
    movem.l %d1-%d3, -(%sp)
    move.w  %d1, %d0
    andi.w  #0x000F, %d0
    or.w    %d7, %d0
    cmpi.w  #0x0030, %d0
    bne.s   .Lnp_not48
    moveq   #2, %d0
    bra.s   .Lnp_done
.Lnp_not48:
    cmpi.w  #0x0033, %d0
    bne.s   .Lnp_general
    moveq   #3, %d0
    bra.s   .Lnp_done
.Lnp_general:
.if RASTAN_GAMEPLAY_HUD_SPRITES != 1
    move.w  %d0, %d2                 /* d2 = effective bank */
    moveq   #0, %d0
    move.b  genesistan_current_scene_id, %d0
    moveq   #PROUTE_OWNER_PC090OJ_ID, %d1
    bsr     palette_route_lookup     /* d0 = line or -1; clobbers d0/d3/a0 */
    tst.l   %d0
    bpl.s   .Lnp_done
    movem.l (%sp), %d1-%d3           /* reload live regs, no pop */
    move.w  %d1, %d0
    andi.w  #0x000F, %d0
    or.w    %d7, %d0
.endif
    lsr.w   #4, %d0
    andi.w  #0x0003, %d0
.Lnp_done:
	    movem.l (%sp)+, %d1-%d3
	    rts

	.if RASTAN_GAMEPLAY_HUD_SPRITES == 2
/* Build 0233 gameplay HUD projection.
 * The arcade score producer writes the P1 score/1UP setup records at 28..36,
 * but the translated gameplay sprite population can reuse part of that range.
 * Project the same packed-BCD P1 score into helper-owned records 0..8 only in
 * gameplay Mode 2, then let the normal object-table -> SAT path handle them.
 */
.Lpc090oj_mode2_project_p1_hud:
	    movem.l %d0-%d7/%a0-%a2, -(%sp)
	    lea     pc090oj_object_ram, %a0
	    movea.l #0x00FF011E, %a2
	    clr.w   %d5                         /* significant digit has appeared */

	    moveq   #0, %d1                     /* 100000s: high nibble FF011E */
	    move.b  (%a2), %d1
	    lsr.b   #4, %d1
	    andi.w  #0x000F, %d1
	    moveq   #0x08, %d4
	    bsr     .Lmode2_emit_digit

	    moveq   #0, %d1                     /* 10000s: low nibble FF011E */
	    move.b  (%a2), %d1
	    andi.w  #0x000F, %d1
	    moveq   #0x10, %d4
	    bsr     .Lmode2_emit_digit
	    subq.l  #1, %a2

	    moveq   #0, %d1                     /* 1000s: high nibble FF011D */
	    move.b  (%a2), %d1
	    lsr.b   #4, %d1
	    andi.w  #0x000F, %d1
	    moveq   #0x18, %d4
	    bsr     .Lmode2_emit_digit

	    moveq   #0, %d1                     /* 100s: low nibble FF011D */
	    move.b  (%a2), %d1
	    andi.w  #0x000F, %d1
	    moveq   #0x20, %d4
	    bsr     .Lmode2_emit_digit
	    subq.l  #1, %a2

	    moveq   #0, %d1                     /* 10s: high nibble FF011C */
	    move.b  (%a2), %d1
	    lsr.b   #4, %d1
	    andi.w  #0x000F, %d1
	    moveq   #0x28, %d4
	    bsr     .Lmode2_emit_digit

	    moveq   #0, %d1                     /* 1s: low nibble FF011C */
	    move.b  (%a2), %d1
	    andi.w  #0x000F, %d1
	    moveq   #0x30, %d4
	    bsr     .Lmode2_emit_digit

	    tst.w   %d5
	    bne.s   .Lmode2_emit_label
	    lea     pc090oj_object_ram + (4 * 8), %a1
	    move.w  #0x0010, 2(%a1)             /* zero score displays as 00 */
	    move.w  #0x0010, 10(%a1)

	.Lmode2_emit_label:
	    clr.w   (%a0)+                      /* record 6: '1' */
	    move.w  #0x0010, (%a0)+
	    move.w  #0x0039, (%a0)+
	    move.w  #0x0040, (%a0)+
	    clr.w   (%a0)+                      /* record 7: 'U' */
	    clr.w   (%a0)+
	    move.w  #0x0048, (%a0)+
	    move.w  #0x0028, (%a0)+
	    clr.w   (%a0)+                      /* record 8: 'P' */
	    clr.w   (%a0)+
	    move.w  #0x0046, (%a0)+
	    move.w  #0x0038, (%a0)+

	    movem.l (%sp)+, %d0-%d7/%a0-%a2
	    rts

.Lmode2_emit_digit:
	    clr.w   (%a0)+
	    move.w  #0x0010, %d6
	    tst.w   %d5
	    bne.s   .Lmode2_digit_visible
	    tst.w   %d1
	    bne.s   .Lmode2_digit_visible
	    move.w  #0x0110, %d6               /* hidden leading zero */
	    bra.s   .Lmode2_digit_store
	.Lmode2_digit_visible:
	    moveq   #1, %d5
	.Lmode2_digit_store:
	    move.w  %d6, (%a0)+
	    addi.w  #0x002A, %d1
	    move.w  %d1, (%a0)+
	    move.w  %d4, (%a0)+
	    rts
	.endif

	/* One ascending pass over the object table into the back shadow-SAT bank.  */
	pc090oj_native_emit_pass:
	    movem.l %d0-%d7/%a0-%a3, -(%sp)
	    lea     staged_sprite_sat, %a3
	    tst.w   pc090oj_sat_bank
	    beq.s   .Lnep_bank_ok
	    lea     staged_sprite_sat_b, %a3
	.Lnep_bank_ok:
	.if RASTAN_GAMEPLAY_HUD_SPRITES == 2
	    cmpi.b  #PC090OJ_SCENE_GAMEPLAY_ID, genesistan_current_scene_id
	    bne.s   .Lnep_no_mode2_p1_hud
	    bsr     .Lpc090oj_mode2_project_p1_hud
	.Lnep_no_mode2_p1_hud:
	.endif
	    lea     sprite_tile_resident_code, %a2
	    lea     pc090oj_cell_used, %a1     /* per-frame referenced-cell bitmap */
	    clr.l   (%a1)+
    clr.l   (%a1)+
    clr.l   (%a1)+
    clr.l   (%a1)+
    moveq   #0, %d5                    /* d5 = emitted count / cursor */
    moveq   #0, %d6                    /* d6 = record */
.Lnep_loop:
.if RASTAN_GAMEPLAY_HUD_SPRITES != 1
    cmpi.w  #46, %d6                   /* records 0..45 = arcade HUD family */
    bhs.s   .Lnep_not_hud
    cmpi.b  #PC090OJ_SCENE_GAMEPLAY_ID, genesistan_current_scene_id
    bne.s   .Lnep_not_hud
		.if RASTAN_GAMEPLAY_HUD_SPRITES == 2
		    /* Build 0233: keep only helper-owned gameplay P1 score records 0..8.
		     * Records 9..45 are reserved/overlapping arcade-HUD family rows. */
	    cmpi.w  #9, %d6
	    blo.s   .Lnep_not_hud
	.endif
	    bra     .Lnep_next
.Lnep_not_hud:
.endif
    move.w  %d5, -(%sp)                /* decode clobbers d5 (cursor) */
	    bsr     .Lpc090oj_decode_record    /* d6 -> d0 draw,d1 w0,d2 Y,d3 code,d4 X,d7 colbank */
	    move.w  (%sp)+, %d5
	    tst.w   %d0
	    beq     .Lnep_next
	.if RASTAN_GAMEPLAY_HUD_SPRITES == 2
		    /* Build 0232: gameplay score/1UP records keep arcade variable-width
		     * visibility, but use a separate white glyph residency variant. */
		    cmpi.b  #PC090OJ_SCENE_GAMEPLAY_ID, genesistan_current_scene_id
		    bne.s   .Lnep_no_hud_white
		    cmpi.w  #9, %d6
		    bhs.s   .Lnep_no_hud_white
	    cmpi.w  #0x002A, %d3
	    blo.s   .Lnep_hud_white_label_check
	    cmpi.w  #0x0034, %d3
	    blo.s   .Lnep_hud_white
	.Lnep_hud_white_label_check:
	    cmpi.w  #0x0039, %d3
	    beq.s   .Lnep_hud_white
	    cmpi.w  #0x0046, %d3
	    beq.s   .Lnep_hud_white
	    cmpi.w  #0x0048, %d3
	    bne.s   .Lnep_no_hud_white
	.Lnep_hud_white:
	    ori.w   #0x8000, %d3              /* residency tag only; VDP tile attrs unchanged */
	.Lnep_no_hud_white:
	.endif
	    /* Build 0222 code-keyed residency: 32 sets x 4 ways over cells 0..127.
	     * Per-frame REFERENCE PROTECTION: a cell used by any entry of the frame
     * being built can never be chosen as a victim, so no displayed sprite can
     * have its patterns stolen (the 0221 wrong-art/disappear mechanism).
     * EMIT-ON-MISS: an enqueued upload lands in VBlank BEFORE the SAT DMA, so
     * a missing code is emitted pointing at its newly assigned cell with an
     * optimistic tag -- residency misses are invisible.  Only queue overflow
     * or a fully-referenced set skips (bounded, counted). */
    move.w  %d3, %d0
    andi.w  #0x001F, %d0
    lsl.w   #3, %d0                    /* d0 = set*8 = way0 tag byte offset */
    cmp.w   0(%a2,%d0.w), %d3
    beq     .Lnep_hit
    addq.w  #2, %d0
    cmp.w   0(%a2,%d0.w), %d3
    beq     .Lnep_hit
    addq.w  #2, %d0
    cmp.w   0(%a2,%d0.w), %d3
    beq     .Lnep_hit
    addq.w  #2, %d0
    cmp.w   0(%a2,%d0.w), %d3
    beq     .Lnep_hit
    /* miss: pick the first way in the set whose cell is unreferenced */
    move.w  %d1, -(%sp)
    move.w  %d3, %d0
    andi.w  #0x001F, %d0
    lsl.w   #3, %d0
    moveq   #3, %d1
.Lnep_vloop:
    bsr     .Lnep_cell_free
    beq.s   .Lnep_take
    addq.w  #2, %d0
    dbra    %d1, .Lnep_vloop
    move.w  (%sp)+, %d1
    addq.w  #1, pc090oj_dropped_count  /* all 4 ways referenced this frame */
    bra     .Lnep_next
.Lnep_take:
    move.w  pc090oj_tile_dma_count, %d1
    cmpi.w  #12, %d1
    bhs.s   .Lnep_qfull
    lea     pc090oj_tile_dma_worklist, %a1
    lsl.w   #2, %d1
    adda.w  %d1, %a1
    move.w  %d0, %d1
    lsr.w   #1, %d1                    /* cell */
    move.w  %d1, (%a1)+
    move.w  %d3, (%a1)                 /* code */
    addq.w  #1, pc090oj_tile_dma_count
    move.w  %d3, 0(%a2,%d0.w)          /* optimistic tag: same-frame re-hits */
    move.w  (%sp)+, %d1
    bra     .Lnep_hit                  /* emit pointing at the enqueued cell */
.Lnep_qfull:
    move.w  (%sp)+, %d1
    addq.w  #1, pc090oj_dropped_count
    bra     .Lnep_next
/* d0 = tag byte offset; returns eq when the cell is NOT referenced this frame.
 * Clobbers a1/flags only. */
.Lnep_cell_free:
    move.w  %d0, -(%sp)
    lea     pc090oj_cell_used, %a1
    lsr.w   #4, %d0
    adda.w  %d0, %a1
    move.w  (%sp), %d0
    lsr.w   #1, %d0
    andi.w  #7, %d0
    btst    %d0, (%a1)
    movem.w (%sp)+, %d0                /* movem: restores d0 WITHOUT touching CCR */
    rts
.Lnep_hit:
    /* mark the cell referenced (protects it for the rest of this frame) */
    move.w  %d0, -(%sp)
    lea     pc090oj_cell_used, %a1
    lsr.w   #4, %d0
    adda.w  %d0, %a1
    move.w  (%sp), %d0
    lsr.w   #1, %d0
    andi.w  #7, %d0
    bset    %d0, (%a1)
    move.w  (%sp)+, %d0
.Lnep_res_ok:
    /* d0 = tag byte offset = cell*2 */
    move.w  %d0, -(%sp)                /* save cell*2 */
    /* word0: Y + bias */
    move.w  %d2, %d0
    andi.w  #0x01FF, %d0
    addi.w  #PC090OJ_SAT_Y_BIAS, %d0
    andi.w  #0x01FF, %d0
    move.w  %d0, (%a3)+
    /* word1: size 16x16 | link = cursor+1 (last patched after the pass) */
    move.w  %d5, %d0
    addq.w  #1, %d0
    andi.w  #0x007F, %d0
    ori.w   #0x0500, %d0
    move.w  %d0, (%a3)+
    /* word2: pri | flips | tile.  Palette bits are resolved at COMMIT time:
     * sprite_ctrl (colbank) is display-latch state the arcade sets AFTER its
     * producers run, so the mainline pass records each entry's bank nibble in
     * a parallel array and the VBlank fix-up applies the latched colbank. */
	    move.w  %d1, %d0
	    andi.w  #0x000F, %d0
	    lea     pc090oj_sat_nibble, %a1
	    move.b  %d0, 0(%a1,%d5.w)
	.if RASTAN_GAMEPLAY_HUD_SPRITES == 2
	    lea     pc090oj_sat_force_line, %a1
	    move.b  #0xFF, 0(%a1,%d5.w)
	    btst    #15, %d3
	    beq.s   .Lnep_no_force_line
	    move.b  #3, 0(%a1,%d5.w)          /* HUD white variant uses CRAM line 3 */
	.Lnep_no_force_line:
	.endif
	    moveq   #0, %d0
	    ori.w   #0x8000, %d0
    btst    #15, %d1                   /* post-flip vflip */
    beq.s   .Lnep_novf
    ori.w   #0x1000, %d0
.Lnep_novf:
    btst    #14, %d1                   /* post-flip hflip */
    beq.s   .Lnep_nohf
    ori.w   #0x0800, %d0
.Lnep_nohf:
    move.w  (%sp)+, %d2                /* cell*2 (Y no longer needed) */
    add.w   %d2, %d2                   /* cell*4 */
    addi.w  #SPRITE_TILE_BASE, %d2
    andi.w  #0x07FF, %d2
    or.w    %d2, %d0
    move.w  %d0, (%a3)+
    /* word3: X + bias */
    move.w  %d4, %d0
    andi.w  #0x01FF, %d0
    addi.w  #PC090OJ_SAT_X_BIAS, %d0
    andi.w  #0x01FF, %d0
    move.w  %d0, (%a3)+
    addq.w  #1, %d5
    cmpi.w  #NATIVE_SAT_MAX, %d5
    bhs.s   .Lnep_done_scan            /* first-80 in ascending arcade order */
.Lnep_next:
    addq.w  #1, %d6
    cmpi.w  #256, %d6
    blo     .Lnep_loop
.Lnep_done_scan:
    tst.w   %d5
    bne.s   .Lnep_have
    clr.w   (%a3)+                     /* zero sprites: hidden terminator */
    clr.w   (%a3)+
    clr.w   (%a3)+
    clr.w   (%a3)+
    bra.s   .Lnep_store
.Lnep_have:
    move.w  -6(%a3), %d0               /* last entry: link = 0 terminates */
    andi.w  #0xFF80, %d0
    move.w  %d0, -6(%a3)
.Lnep_store:
    move.w  %d5, pc090oj_emitted_count
    move.w  #1, pc090oj_sat_frame_ready
    move.w  #1, pc090oj_sat_dirty
    movem.l (%sp)+, %d0-%d7/%a0-%a3
    rts

/* Commit-time palette resolution: apply the DISPLAY-LATCHED colbank to every
 * emitted entry (<=80 iterations).  d7 = colbank from the current sprite_ctrl
 * shadow; per entry d1 = stored bank nibble -> .Lnative_palsel line. */
.Lnative_pal_fixup:
    movem.l %d0-%d7/%a0-%a3, -(%sp)
    move.w  pc090oj_emitted_count, %d6
    beq.s   .Lnpf_done
    lea     staged_sprite_sat, %a3
    tst.w   pc090oj_sat_front
    beq.s   .Lnpf_base_ok
    lea     staged_sprite_sat_b, %a3
	.Lnpf_base_ok:
	    lea     pc090oj_sat_nibble, %a2
	.if RASTAN_GAMEPLAY_HUD_SPRITES == 2
	    lea     pc090oj_sat_force_line, %a1
	.endif
	    move.w  pc090oj_sprite_ctrl_shadow, %d7
	    andi.w  #0x00E0, %d7
	    lsr.w   #1, %d7
	    moveq   #0, %d5
	.Lnpf_loop:
	    moveq   #0, %d1
	    move.b  0(%a2,%d5.w), %d1
	.if RASTAN_GAMEPLAY_HUD_SPRITES == 2
	    moveq   #0, %d0
	    move.b  0(%a1,%d5.w), %d0
	    cmpi.b  #0xFF, %d0
	    bne.s   .Lnpf_line_ready
	.endif
	    bsr     .Lnative_palsel            /* d1 nibble + d7 colbank -> d0 line */
	.Lnpf_line_ready:
	    lsl.w   #8, %d0
	    lsl.w   #5, %d0
    move.w  4(%a3), %d1
    andi.w  #0x9FFF, %d1               /* clear palette bits */
    or.w    %d0, %d1
    move.w  %d1, 4(%a3)
    adda.w  #8, %a3
    addq.w  #1, %d5
    cmp.w   %d6, %d5
    blo.s   .Lnpf_loop
.Lnpf_done:
    movem.l (%sp)+, %d0-%d7/%a0-%a3
    rts

/* VBlank entry (called by _vblank_service): frontend fallback pass only.    */
vdp_prepare_sprites:
    tst.w   pc090oj_sat_frame_ready
    bne.s   .Lvps_done
    bsr     pc090oj_native_emit_pass
.Lvps_done:
    rts

/* VBlank commit: pattern uploads, then publish+DMA the finished bank.       */
vdp_commit_sprites:
vdp_commit_sprites_vram:
    movem.l %d0-%d7/%a0-%a6, -(%sp)
    bsr     .Lvcs_tile_dma
    tst.w   pc090oj_sat_frame_ready
    beq.s   .Lvcs_commit_done
    move.w  pc090oj_sat_bank, pc090oj_sat_front
    eori.w  #1, pc090oj_sat_bank
    clr.w   pc090oj_sat_frame_ready
    bsr     .Lnative_pal_fixup
    bsr     .Lvcs_sat_dma
    clr.w   pc090oj_sat_dirty
.Lvcs_commit_done:
    movem.l (%sp)+, %d0-%d7/%a0-%a6
    rts

.Lpc090oj_decode_record:
    move.w  %d6, %d0
    lsl.w   #3, %d0
    lea     pc090oj_object_ram, %a0
    adda.w  %d0, %a0
    move.w  (%a0), %d1
    move.w  2(%a0), %d2
    move.w  4(%a0), %d3
    move.w  6(%a0), %d4

    andi.w  #0x1FFF, %d3
    beq     .Ldecode_notdraw
    cmpi.w  #0x1000, %d3
    bhs     .Ldecode_notdraw
    move.w  %d3, %d5
    lsr.w   #3, %d5
    lea     pc090oj_blank_code_bitset, %a1
    move.b  0(%a1,%d5.w), %d5
    move.w  %d3, %d0
    andi.w  #0x0007, %d0
    btst    %d0, %d5
    bne     .Ldecode_notdraw

    andi.w  #0x01FF, %d2
    cmpi.w  #0x0140, %d2
    bls.s   .Ldecode_y_ok
    subi.w  #0x0200, %d2
.Ldecode_y_ok:
    andi.w  #0x01FF, %d4
    cmpi.w  #0x0140, %d4
    bls.s   .Ldecode_x_ok
    subi.w  #0x0200, %d4
.Ldecode_x_ok:
    move.w  pc090oj_ctrl_shadow, %d5
    btst    #0, %d5
    bne.s   .Ldecode_no_flip
    move.w  #PC090OJ_FLIP_X_TERM, %d5
    sub.w   %d4, %d5
    move.w  %d5, %d4
    move.w  #PC090OJ_FLIP_Y_TERM, %d5
    sub.w   %d2, %d5
    move.w  %d5, %d2
    eori.w  #0xC000, %d1
.Ldecode_no_flip:
    /* Arcade -> Genesis viewport origin: aligns sprites with the background
     * (which applies the matching bias in vdp_comm.s) and places the arcade top
     * margin above the Genesis viewport, where clipped records drop out. */
    addi.w  #PC090OJ_TO_GENESIS_X_OFFSET, %d4
    addi.w  #PC090OJ_TO_GENESIS_Y_OFFSET, %d2

    /* Opaque-geometry viewport clip.  A record is drawable only when at least
     * one opaque pixel of its post-flip pattern intersects the effective clip
     * rectangle; fully-clipped records return not-drawable, so they receive no
     * SAT slot, link entry, tile work, or scanline capacity.  d3 = code
     * (0..0x0FFF); box bytes = [min_row, max_row, min_col, max_col] (unflipped). */
    move.w  %d3, %d0
    andi.w  #0x0FFF, %d0
    lsl.w   #2, %d0
    lea     pc090oj_opaque_bbox, %a1
    adda.w  %d0, %a1
    /* vertical opaque span (post vertical-flip) vs [TOP, BOTTOM) */
    moveq   #0, %d0
    move.b  0(%a1), %d0                    /* min_row */
    moveq   #0, %d5
    move.b  1(%a1), %d5                    /* max_row */
    btst    #15, %d1                       /* vflip (post-flip word0 bit 15) */
    beq.s   .Ldecode_vrows_ok
    neg.w   %d0
    addi.w  #PC090OJ_PATTERN_MAX_ROW, %d0  /* MAX_ROW - min_row */
    neg.w   %d5
    addi.w  #PC090OJ_PATTERN_MAX_ROW, %d5  /* MAX_ROW - max_row */
    exg     %d0, %d5                       /* d0 = eff top row, d5 = eff bottom row */
.Ldecode_vrows_ok:
    add.w   %d2, %d0                       /* opaque top    (screen Y) */
    add.w   %d2, %d5                       /* opaque bottom (screen Y) */
    cmpi.w  #GENESIS_VIEWPORT_BOTTOM, %d0
    bge     .Ldecode_notdraw               /* opaque top at/below viewport bottom */
    cmpi.w  #GENESIS_VIEWPORT_TOP, %d5
    blt     .Ldecode_notdraw               /* opaque bottom above viewport top */
    /* horizontal opaque span (post horizontal-flip) vs [LEFT, RIGHT) */
    moveq   #0, %d0
    move.b  2(%a1), %d0                    /* min_col */
    moveq   #0, %d5
    move.b  3(%a1), %d5                    /* max_col */
    btst    #14, %d1                       /* hflip (post-flip word0 bit 14) */
    beq.s   .Ldecode_hcols_ok
    neg.w   %d0
    addi.w  #PC090OJ_PATTERN_MAX_COL, %d0  /* MAX_COL - min_col */
    neg.w   %d5
    addi.w  #PC090OJ_PATTERN_MAX_COL, %d5  /* MAX_COL - max_col */
    exg     %d0, %d5                       /* d0 = eff left col, d5 = eff right col */
.Ldecode_hcols_ok:
    add.w   %d4, %d0                       /* opaque left  (screen X) */
    add.w   %d4, %d5                       /* opaque right (screen X) */
    cmpi.w  #GENESIS_VIEWPORT_RIGHT, %d0
    bge     .Ldecode_notdraw               /* opaque left at/right of viewport right */
    cmpi.w  #GENESIS_VIEWPORT_LEFT, %d5
    blt     .Ldecode_notdraw               /* opaque right left of viewport left */
    andi.w  #0x0FFF, %d3
    move.w  pc090oj_sprite_ctrl_shadow, %d7
    andi.w  #0x00E0, %d7
    lsr.w   #1, %d7
    moveq   #1, %d0
    rts
.Ldecode_notdraw:
    moveq   #0, %d0
    rts

/* Generic bitmap scans (base-68000; a1=base, d5=total bits). */
/* First SET bit >= d0.  Returns d0 = bit or d5.  Clobbers d1-d3. */

/*
 * Precomputed tile-DMA worklist commit.  Bounded by pc090oj_tile_dma_count,
 * skips canceled entries (code 0xFFFF), updates slot residency only after the
 * DMA, and resets the reservation map + count at the end of the interval.
 */
.Lvcs_tile_dma:
    move.w  pc090oj_tile_dma_count, %d7
    beq     .Lvcs_tile_reset
    moveq   #0, %d5
.Lvcs_tile_loop:
    move.w  %d5, %d0
    lsl.w   #2, %d0
    lea     pc090oj_tile_dma_worklist, %a0
    adda.w  %d0, %a0
    move.w  (%a0), %d4                  /* slot */
    move.w  2(%a0), %d6                /* code (0xFFFF = canceled) */
    cmpi.w  #0xFFFF, %d6
    beq     .Lvcs_tile_next

	    move.w  %d6, %d0
	    andi.w  #0x0FFF, %d0
	.if RASTAN_GAMEPLAY_HUD_SPRITES == 2
	    btst    #15, %d6
	    beq.s   .Lvcs_tile_src_normal
	    move.w  %d0, %d3
	    subi.w  #0x002A, %d3
	    mulu.w  #128, %d3
	    lea     rastan_pc090oj_hud_white, %a1
	    adda.l  %d3, %a1
	    bra.s   .Lvcs_tile_src_ready
	.Lvcs_tile_src_normal:
	.endif
	    mulu.w  #128, %d0
	    lea     rastan_pc090oj, %a1
	    adda.l  %d0, %a1
	.Lvcs_tile_src_ready:
	    move.l  %a1, %d0
    lsr.l   #1, %d0
    movea.l #VDP_CTRL, %a3
    move.w  #0x9340, (%a3)
    move.w  #0x9400, (%a3)
    move.w  %d0, %d3
    andi.w  #0x00FF, %d3
    ori.w   #0x9500, %d3
    move.w  %d3, (%a3)
    move.l  %d0, %d3
    lsr.l   #8, %d3
    andi.w  #0x00FF, %d3
    ori.w   #0x9600, %d3
    move.w  %d3, (%a3)
    move.l  %d0, %d3
    lsr.l   #8, %d3
    lsr.l   #8, %d3
    andi.w  #0x007F, %d3
    ori.w   #0x9700, %d3
    move.w  %d3, (%a3)
    move.w  %d4, %d0
    lsl.w   #2, %d0
    addi.w  #SPRITE_TILE_BASE, %d0
    lsl.l   #5, %d0
    move.l  %d0, %d1
    andi.l  #0x00003FFF, %d1
    swap    %d1
    move.l  %d0, %d2
    lsr.l   #8, %d2
    lsr.l   #6, %d2
    andi.l  #0x00000003, %d2
    ori.l   #0x40000080, %d1
    or.l    %d2, %d1
    move.l  %d1, (%a3)
    move.w  %d4, %d0
    add.w   %d0, %d0
    lea     sprite_tile_resident_code, %a1
    move.w  %d6, 0(%a1,%d0.w)
.Lvcs_tile_next:
    addq.w  #1, %d5
    cmp.w   %d7, %d5
    blo     .Lvcs_tile_loop
.Lvcs_tile_reset:
    /* Reset only the slots actually reserved this interval (d7 = count, still
     * live), so a stable no-work frame (count 0) does zero reset work. */
    tst.w   %d7
    beq.s   .Lvcs_tile_reset_done
    moveq   #0, %d5
.Lvcs_tile_reset_loop:
    move.w  %d5, %d0
    lsl.w   #2, %d0
    lea     pc090oj_tile_dma_worklist, %a0
    adda.w  %d0, %a0
    moveq   #0, %d0
    move.w  (%a0), %d0                  /* reserved slot for this entry */
    lea     worklist_entry_for_slot, %a1
    move.b  #0xFF, 0(%a1,%d0.w)
    addq.w  #1, %d5
    cmp.w   %d7, %d5
    blo.s   .Lvcs_tile_reset_loop
.Lvcs_tile_reset_done:
    clr.w   pc090oj_tile_dma_count
    rts

/* SAT DMA: length = max(highest_used+1, 1) * 4 words, clamped to 80 slots. */
.Lvcs_sat_dma:
    movea.l #VDP_CTRL, %a3
    move.w  #80, %d0                   /* constant full-table DMA (640 B) */
    lsl.w   #2, %d0

    move.w  %d0, %d1
    andi.w  #0x00FF, %d1
    ori.w   #0x9300, %d1
    move.w  %d1, (%a3)

    move.w  %d0, %d1
    lsr.w   #8, %d1
    andi.w  #0x00FF, %d1
    ori.w   #0x9400, %d1
    move.w  %d1, (%a3)

    move.l  #staged_sprite_sat, %d0
    tst.w   pc090oj_sat_front
    beq.s   .Lsat_src_ok
    move.l  #staged_sprite_sat_b, %d0
.Lsat_src_ok:
    lsr.l   #1, %d0

    move.w  %d0, %d1
    andi.w  #0x00FF, %d1
    ori.w   #0x9500, %d1
    move.w  %d1, (%a3)

    move.l  %d0, %d1
    lsr.l   #8, %d1
    andi.w  #0x00FF, %d1
    ori.w   #0x9600, %d1
    move.w  %d1, (%a3)

    move.l  %d0, %d1
    lsr.l   #8, %d1
    lsr.l   #8, %d1
    andi.w  #0x007F, %d1
    ori.w   #0x9700, %d1
    move.w  %d1, (%a3)

    move.l  #0x0000F800, %d0
    move.l  %d0, %d1
    andi.l  #0x00003FFF, %d1
    swap    %d1
    move.l  %d0, %d2
    lsr.l   #8, %d2
    lsr.l   #6, %d2
    andi.l  #0x00000003, %d2
    ori.l   #0x40000080, %d1
    or.l    %d2, %d1
    move.l  %d1, (%a3)
    rts

/* ------------------------------------------------------------------------- */
/* VRAM DMA self-test                                                        */
/* ------------------------------------------------------------------------- */

genesistan_pc090oj_dma_self_test:
    movem.l %d0-%d7/%a0-%a6, -(%sp)

    /* Stack buffer (128 bytes) */
    lea     -128(%sp), %sp
    movea.l %sp, %a6

    /* DMA source: rastan_pc090oj + 0x80, len 64 words, dest VRAM 0x8000 */
    lea     rastan_pc090oj+0x80, %a1
    move.l  %a1, %d0
    lsr.l   #1, %d0

    movea.l #VDP_CTRL, %a3
    move.w  #0x9340, (%a3)
    move.w  #0x9400, (%a3)

    move.w  %d0, %d1
    andi.w  #0x00FF, %d1
    ori.w   #0x9500, %d1
    move.w  %d1, (%a3)

    move.l  %d0, %d1
    lsr.l   #8, %d1
    andi.w  #0x00FF, %d1
    ori.w   #0x9600, %d1
    move.w  %d1, (%a3)

    move.l  %d0, %d1
    lsr.l   #8, %d1
    lsr.l   #8, %d1
    andi.w  #0x007F, %d1
    ori.w   #0x9700, %d1
    move.w  %d1, (%a3)

    move.l  #0x00008000, %d0
    move.l  %d0, %d1
    andi.l  #0x00003FFF, %d1
    swap    %d1
    move.l  %d0, %d2
    lsr.l   #8, %d2
    lsr.l   #6, %d2
    andi.l  #0x00000003, %d2
    ori.l   #0x40000080, %d1
    or.l    %d2, %d1
    move.l  %d1, (%a3)

    /* Read back VRAM 0x8000..0x807F into stack buffer */
    move.l  #0x00008000, %d0
    move.l  %d0, %d1
    andi.l  #0x00003FFF, %d1
    swap    %d1
    move.l  %d0, %d2
    lsr.l   #8, %d2
    lsr.l   #6, %d2
    andi.l  #0x00000003, %d2
    or.l    %d2, %d1                 /* VRAM read command (no write/dma bits) */
    move.l  %d1, (%a3)

    movea.l #VDP_DATA, %a4
    move.w  #(64 - 1), %d0
.Lpc090oj_dma_read_loop:
    move.w  (%a4), (%a6)+
    dbra    %d0, .Lpc090oj_dma_read_loop

    /* Compare 64 words */
    lea     rastan_pc090oj+0x80, %a0
    movea.l %sp, %a1
    moveq   #0, %d6
    move.w  #(64 - 1), %d0
.Lpc090oj_dma_cmp_loop:
    move.w  (%a0)+, %d1
    move.w  (%a1)+, %d2
    cmp.w   %d1, %d2
    bne.s   .Lpc090oj_dma_fail
    addq.w  #1, %d6
    dbra    %d0, .Lpc090oj_dma_cmp_loop

    lea     128(%sp), %sp
    movem.l (%sp)+, %d0-%d7/%a0-%a6
    rts

.Lpc090oj_dma_fail:
    move.w  %d6, pc090oj_dma_test_mismatch_offset
    move.w  %d1, pc090oj_dma_test_expected_word
    move.w  %d2, pc090oj_dma_test_actual_word

    /* copy full 128-byte snapshot */
    movea.l %sp, %a0
    lea     pc090oj_dma_test_actual_buffer, %a1
    move.w  #(128/2 - 1), %d0
.Lpc090oj_dma_copy_buf:
    move.w  (%a0)+, (%a1)+
    dbra    %d0, .Lpc090oj_dma_copy_buf

    move.w  #0x6F0E, pc090oj_dma_test_fired_flag

.Lpc090oj_dma_test_halt:
    move.b  pc090oj_dma_test_heartbeat, %d0
    addq.b  #1, %d0
    move.b  %d0, pc090oj_dma_test_heartbeat
    bra     .Lpc090oj_dma_test_halt

/* ------------------------------------------------------------------------- */
/* BSS                                                                        */
/* ------------------------------------------------------------------------- */

    .section .bss
    .align 2

/* N1 shadow SAT double buffer (final Genesis SAT format, link-ordered). */
staged_sprite_sat:
    .space (80 * 8)
staged_sprite_sat_b:
    .space (80 * 8)
pc090oj_sat_bank:
    .word 0
pc090oj_sat_front:
    .word 0
pc090oj_sat_frame_ready:
    .word 0
pc090oj_sat_nibble:
	    .space 80
pc090oj_sat_force_line:
	    .space 80
	    .align 2
/* Per-frame referenced-cell bitmap (128 bits). */
pc090oj_cell_used:
    .space 16
/* Code-keyed residency tags: 64 sets x 2 ways = 128 cells (tiles 1024..1535). */
sprite_tile_resident_code:
    .space (128 * 2)
/* Bounded VBlank pattern-upload queue: 12 x {word cell, word code}. */
pc090oj_tile_dma_worklist:
    .space (12 * 4)
pc090oj_tile_dma_count:
    .word 0
/* The arcade program's persistent slot-addressed object store (256 rows).
 * This is arcade state (incremental producers update rows in place), not a
 * chip mirror: nothing scans, diffs, or reverse-converts it except the one
 * per-frame native emit pass. Fixed 256 rows: no mirror-size configuration. */
pc090oj_object_ram:
    .space (256 * 8)
pc090oj_ctrl_shadow:
    .word 0
pc090oj_sprite_ctrl_shadow:
    .word 0
pc090oj_mirror_dirty:
    .word 0
pc090oj_candidate_count:
    .word 0
pc090oj_decoded_count:
    .word 0
pc090oj_code_zero_skipped_count:
    .word 0
pc090oj_blank_skipped_count:
    .word 0
pc090oj_unmapped_skipped_count:
    .word 0
pc090oj_offscreen_skipped_count:
    .word 0
pc090oj_hud_suppressed_count:
    .word 0
pc090oj_drawable_count:
    .word 0
pc090oj_emitted_count:
    .word 0
pc090oj_dropped_count:
    .word 0
pc090oj_scan_colbank:
    .word 0
pc090oj_scan_active:
    .word 0
pc090oj_producer_oob_count:
    .word 0
pc090oj_producer_write_count:
    .word 0
pc090oj_represented_count:
    .word 0
pc090oj_sat_dirty:
    .word 0
pc090oj_bootstrap_pending:
    .word 0
.Lscratch_rec:
    .word 0
.Lrecord46_rec:
    .word 0
.Lrecord46_count:
    .word 0
    .align 2
.Lrecord46_scratch:
    .space 8
/* Audit-guard + DMA self-test diagnostics (retained consumers). */
audit_guard_caller_pc:
    .long 0
audit_guard_register_snapshot:
    .space (16 * 4)
audit_guard_vcount:
    .word 0
audit_guard_fired_flag:
    .word 0
audit_guard_heartbeat:
    .word 0
    .align 2

/* Legacy exported stubs (symbols retained; no runtime consumers). */
staged_sprite_dirty:
    .long 0
staged_sprite_active_count:
    .word 0
staged_sprite_descriptor_table:
pc090oj_candidate_bitset:
record_to_slot:
represented_records:
waiting_records:
used_sat_slots:
worklist_entry_for_slot:
    .space 4
    .align 2

    .section .bss.patcher
    .balign 2
pc090oj_dma_test_fired_flag:
    .word 0
pc090oj_dma_test_mismatch_offset:
    .word 0
pc090oj_dma_test_expected_word:
    .word 0
pc090oj_dma_test_actual_word:
    .word 0
pc090oj_dma_test_actual_buffer:
    .space 128
pc090oj_dma_test_heartbeat:
    .byte 0
