    .section .rodata,"a"
    .align 2
    .global rastan_pc090oj
rastan_pc090oj:
    .incbin "../../build/pc090oj_genesis.bin"

    .global pc090oj_slot_lut
    .align 2
pc090oj_slot_lut:
    .incbin "../../build/pc090oj_slot_lut.bin"

    .global pc090oj_blank_code_bitset
    .align 2
pc090oj_blank_code_bitset:
    .incbin "../../build/pc090oj_blank_bitset.bin"

    /* Build 0147: per-code opaque bounding box (4 bytes/code:
     * min_row, max_row, min_col, max_col in unflipped 16x16 cell space).
     * Consumed by .Lpc090oj_decode_record for the opaque-geometry viewport
     * clip. Generated by tools/translation/build_pc090oj_opaque_bbox.py. */
    .global pc090oj_opaque_bbox
    .align 2
pc090oj_opaque_bbox:
    .incbin "../../build/pc090oj_opaque_bbox.bin"
