#ifndef RASTAN_BUILD_INFO_H
#define RASTAN_BUILD_INFO_H

#define RASTAN_BUILD_NUMBER 180
#define RASTAN_BUILD_STAMP "20260324_222216"
#define RASTAN_BUILD_VARIANT "world_rev1"
#define RASTAN_BUILD_HOOK_MODE "hooked"
#define RASTAN_BUILD_LINE "WORLD REV1 BASELINE UI 180 H"

#endif
