#ifndef RASTAN_BUILD_INFO_H
#define RASTAN_BUILD_INFO_H

#define RASTAN_BUILD_NUMBER 84
#define RASTAN_BUILD_STAMP "20260318_000751"
#define RASTAN_BUILD_VARIANT "world_rev1"
#define RASTAN_BUILD_HOOK_MODE "hooked"
#define RASTAN_BUILD_LINE "WORLD REV1 BASELINE UI 84 H"

#endif
