#ifndef RASTAN_BUILD_INFO_H
#define RASTAN_BUILD_INFO_H

#define RASTAN_BUILD_NUMBER 102
#define RASTAN_BUILD_STAMP "20260321_121702"
#define RASTAN_BUILD_VARIANT "world_rev1"
#define RASTAN_BUILD_HOOK_MODE "debug-hooked"
#define RASTAN_BUILD_LINE "WORLD REV1 BASELINE UI 102 H"

#endif
